import { describe, expect, test } from "bun:test";
import { InstancedMesh, Mesh } from "three";
import source from "../src/data/cityWestCinemasV166Source.json";
import { createCityWestCinemasV166, createMinecraftCityWestCinemasV166 } from "../src/CityWestCinemasV166";
import { CITYWEST_CINEMAS_V166_PRISM_IDS, cityWestCinemasV166SourceColumn, cityWestCinemasV166RoofAt } from "../src/cityWestCinemasV166Profile";
function metrics(root:ReturnType<typeof createCityWestCinemasV166>){let calls=0,bytes=0,instances=0;root.traverse(o=>{expect(o.matrixAutoUpdate).toBe(false);if(o instanceof Mesh){calls++;for(const a of Object.values(o.geometry.attributes))bytes+=a.array.byteLength;bytes+=o.geometry.index?.array.byteLength??0;if(o instanceof InstancedMesh){bytes+=o.instanceMatrix.array.byteLength+(o.instanceColor?.array.byteLength??0);instances+=o.count;}expect(o.userData.textureFree).toBe(true);}});return{calls,bytes,instances};}
describe("City West exact source refinement",()=>{
 test("same complete drawn geometry on pointer and touch with bounded independent native blocks",()=>{const full=metrics(createCityWestCinemasV166()),touch=metrics(createCityWestCinemasV166({mobileLike:true})),native=metrics(createMinecraftCityWestCinemasV166());expect(full).toEqual(touch);expect(full.calls).toBe(3);expect(full.bytes).toBeLessThan(2_500_000);expect(native.calls).toBe(1);expect(native.bytes).toBeLessThan(2_500_000);expect(native.instances).toBeGreaterThan(source.nativeBlocks.length);console.log({full,native});});
 test("all measured parents and source roof triangles retain identity",()=>{expect(source.parents.length).toBe(21);expect(source.parts.length).toBe(95);expect(source.parents.some(p=>p.id==="DEBE00YY1EZ0000e")).toBe(false);expect(source.parents.some(p=>p.id==="DEBE04YY500004MZ")).toBe(true);expect(source.parts.filter(p=>p.parentId==="DEBE04YY50002Xuw")).toHaveLength(7);expect(CITYWEST_CINEMAS_V166_PRISM_IDS.has("23010077")).toBe(true);for(const s of source.surfaces.filter(s=>s.kind==="RoofSurface")){for(const[a,b,c]of s.triangles){const x=(a[0]+b[0]+c[0])/3,z=(a[2]+b[2]+c[2])/3;const y=cityWestCinemasV166RoofAt(x,z);if(y!==null)expect(y+1e-4).toBeGreaterThanOrEqual((a[1]+b[1]+c[1])/3);}}});
 test("source suppression requires original footprint and quantized source height",()=>{const p=source.legacyPrisms.find(p=>p.id==="23010077")!;const tri=source.surfaces.find(s=>s.partId===source.parts.find(p=>p.parentId==="DEBE00YY1EZ0000h")!.id&&s.kind==="RoofSurface")!.triangles[0];const x=tri.reduce((s,p)=>s+p[0],0)/3,z=tri.reduce((s,p)=>s+p[2],0)/3;expect(cityWestCinemasV166SourceColumn(x,z,p.y0_dm/10,p.y0_dm/10+Math.ceil(p.h_dm/40)*4+12)).toBe(false);expect(cityWestCinemasV166SourceColumn(-2600,1200,5.2,25.2)).toBe(false);});
});
