import { describe, expect, test } from "bun:test";
import { BoxGeometry, InstancedMesh, Mesh } from "three";
import { createEastSquaresV163, createMinecraftEastSquaresV163 } from "../src/EastSquaresV163";
import { EAST_SQUARES_V163_SOURCE as S, EAST_SQUARES_V163_OSM_KEYS, eastSquaresV163SolidAt } from "../src/eastSquaresV163Profile";
import { surroundingScopeGroundAt } from "../src/surroundingCityScope";
function signature(root:ReturnType<typeof createEastSquaresV163>):string {
  const h=new Bun.CryptoHasher("sha256");root.traverse(o=>{if(!(o instanceof Mesh))return;for(const a of Object.values(o.geometry.attributes))h.update(a.array);if(o.geometry.index)h.update(o.geometry.index.array);if(o instanceof InstancedMesh){h.update(o.instanceMatrix.array);if(o.instanceColor)h.update(o.instanceColor.array);}});return h.digest("hex");
}
function budget(root:ReturnType<typeof createEastSquaresV163>):{bytes:number;renderables:number;instances:number;triangles:number} {
  const geometries=new Set();let bytes=0,renderables=0,instances=0,triangles=0;
  root.traverse(o=>{if(!(o instanceof Mesh))return;renderables++;if(!geometries.has(o.geometry)){geometries.add(o.geometry);for(const a of Object.values(o.geometry.attributes))bytes+=a.array.byteLength;if(o.geometry.index)bytes+=o.geometry.index.array.byteLength;}triangles+=(o.geometry.index?.count??o.geometry.getAttribute("position").count)/3*(o instanceof InstancedMesh?o.count:1);if(o instanceof InstancedMesh){instances+=o.count;bytes+=o.instanceMatrix.array.byteLength+(o.instanceColor?.array.byteLength??0);}for(const m of Array.isArray(o.material)?o.material:[o.material])expect((m as any).map??null).toBeNull();});return{bytes,renderables,instances,triangles};
}
describe("source-bound eastern square landmarks",()=>{
 test("all mapped anchors, outlines and common display ground are retained",()=>{expect(EAST_SQUARES_V163_OSM_KEYS).toEqual(["way/52564405","way/417529567","way/24240866"]);for(const f of Object.values(S.features)){expect(f.outlineXZ[0]).toEqual(f.outlineXZ.at(-1)!);expect(surroundingScopeGroundAt(...f.centerXZ as [number,number])).toBe(3);}expect(S.features.worldClock.osmHeightTag).toBe("0");expect(S.conflicts.some(c=>c.includes("2027"))).toBe(true);});
 test("touch preserves every drawn geometry and instance byte",()=>{expect(signature(createEastSquaresV163(true))).toBe(signature(createEastSquaresV163(false)));});
 test("structural counts match primary descriptions",()=>{const [ring,fountain,clock]=createEastSquaresV163().children;expect(ring.userData.roleCounts["copper relief panel"]).toBe(16);expect(ring.userData.roleCounts["ring support"]).toBe(8);expect(ring.userData.roleCounts["outer water jet"]).toBe(43);expect(fountain.userData.roleCounts["rhombic copper bowl"]).toBe(17);expect(fountain.userData.roleCounts["lower basin spout"]).toBe(8);expect(clock.userData.roleCounts["time zone face"]).toBe(24);expect(clock.userData.roleCounts["planet orbit"]).toBe(8);});
 test("drawn surface construction stays finite, local and bounded",()=>{const root=createEastSquaresV163(),b=budget(root);expect(b.renderables).toBe(9);expect(b.bytes).toBeLessThan(650000);expect(b.instances).toBeLessThan(2600);expect(b.triangles).toBeLessThan(150000);for(const group of root.children)group.traverse(o=>{if(!(o instanceof Mesh))return;expect(o.matrixAutoUpdate).toBe(false);for(const n of o.geometry.getAttribute("position").array)expect(Number.isFinite(n)).toBe(true);if(o instanceof InstancedMesh)for(let i=0;i<o.count;i++){const a=o.instanceMatrix.array;expect(a[i*16+12]).toBeGreaterThan(2750);expect(a[i*16+12]).toBeLessThan(3900);expect(a[i*16+13]).toBeGreaterThan(2.8);expect(a[i*16+13]).toBeLessThan(22);}});});
 test("Minecraft uses three independently authored cube-only batches",()=>{const root=createMinecraftEastSquaresV163(),b=budget(root);expect(b.renderables).toBe(3);expect(b.bytes).toBeLessThan(1500000);expect(b.instances).toBeLessThan(18000);root.traverse(o=>{if(!(o instanceof Mesh))return;expect(o).toBeInstanceOf(InstancedMesh);expect(o.geometry).toBeInstanceOf(BoxGeometry);const m=o as InstancedMesh;for(let i=0;i<m.count;i++)for(const index of[1,2,4,6,8,9])expect(m.instanceMatrix.array[i*16+index]).toBe(0);});expect(signature(createMinecraftEastSquaresV163(true))).toBe(signature(root));});
 test("clock underside and fountain approaches stay open",()=>{const [x,z]=S.features.worldClock.centerXZ;expect(eastSquaresV163SolidAt(x,z,4,.42)).toBe(true);expect(eastSquaresV163SolidAt(x+2,z,4,.42)).toBe(false);expect(eastSquaresV163SolidAt(x,z,6,.42)).toBe(false);for(const f of Object.values(S.features))for(let i=0;i<8;i++){const a=i*Math.PI/4;expect(eastSquaresV163SolidAt(f.centerXZ[0]+Math.cos(a)*18,f.centerXZ[1]+Math.sin(a)*18,3,.42)).toBe(false);}});
 test("all visual sources are credited and no photo is packaged",()=>{expect(S.photographsBundled).toBe(false);expect(S.photographs).toHaveLength(3);for(const p of S.photographs){expect(p.license).toMatch(/^CC BY-SA/);expect(p.sourceUrl).toStartWith("https://commons.wikimedia.org/wiki/File:");expect(p.author.length).toBeGreaterThan(5);}});
});
