import { describe, expect, test } from "bun:test";
import { BoxGeometry, Group, InstancedMesh, Matrix4, Mesh, MeshBasicMaterial, Raycaster, Vector3 } from "three";
import { createTopographyTerrorArchitecture as create, createMinecraftTopographyTerrorArchitecture as createMc, topographyMuseumWalls, topographyAuthoredSolids, topographyAuthoredSolidAt, topographyAuthoredTopAt, type TopographyBlock } from "../src/TopographyTerrorArchitecture";
import { TOPOGRAPHY_TERROR_SOURCE as S, TOPOGRAPHY_TERROR_MUSEUM as M, TOPOGRAPHY_TERROR_TOP, topographyMuseumContains, topographyMuseumTopAt, topographySourceColumnContains, topographySiteSurfaceAt, topographySourceGroundAt, topographyPointInRing } from "../src/topographyTerrorProfile";
import prismJson from "../public/mesh/regierungsviertel/lod2-prisms.json";
import voxelJson from "../public/mesh/regierungsviertel/minecraft-voxels.json";
import { worldGroundSampler, createGroundSlabs, type VoxelPayload } from "../src/MinecraftVoxelWorld";
const rawCells:number[][]=[];const vox=voxelJson as unknown as VoxelPayload;
vox.building_rows!.forEach((row,zi)=>{const z=(vox.grid.min_z_idx+zi+.5)*vox.cell_m;if(z<1295||z>1466)return;for(const[xi,n,lo,hi]of row)for(let j=0;j<n;j++){const x=(vox.grid.min_x_idx+xi+j+.5)*vox.cell_m;if(x>699&&x<963)rawCells.push([x,z,lo/10,hi/10]);}});
function sourceCells():InstancedMesh{const cells=rawCells.filter(([x,z,lo,hi])=>!topographySourceColumnContains(x,z,lo,hi,vox.cell_m)),mesh=new InstancedMesh(new BoxGeometry(1,1,1),new MeshBasicMaterial(),cells.length),m=new Matrix4();cells.forEach(([x,z,lo,hi],i)=>{m.makeScale(vox.cell_m,hi-lo,vox.cell_m).setPosition(x,(lo+hi)/2,z);mesh.setMatrixAt(i,m);});mesh.name="retained source voxel columns";mesh.computeBoundingSphere();return mesh;}
describe("Topographie des Terrors architecture",()=>{
 test("preserves exact source records and independently sourced Wall routes",()=>{expect(S.prisms).toHaveLength(5);for(const p of S.prisms)expect(p).toEqual(prismJson.buildings.find(x=>x.id===p.id));expect(M.id).toBe("400002h6");expect(M.holes).toHaveLength(1);expect(TOPOGRAPHY_TERROR_TOP).toBe(13.2);expect(S.site.tags.id).toBe("24368681");expect(S.trench.tags.id).toBe("281621233");expect(S.cellar.tags.id).toBe("639831712");expect(S.officialWall.id).toBe("85");expect(S.osmWall.tags.id).toBe("591200192");expect(S.officialWall.lengthM).toBeCloseTo(195.799876,5);expect(S.officialWall.line).not.toEqual(S.osmWall.line);});
 test("source facade normals point outside all walls including the court",()=>{const walls=topographyMuseumWalls();expect(walls).toHaveLength(8);for(const w of walls){const x=(w.a[0]+w.b[0])/2,z=(w.a[1]+w.b[1])/2;expect(Math.hypot(w.nx,w.nz)).toBeCloseTo(1,8);expect(topographyMuseumContains(x+w.nx*.02,z+w.nz*.02)).toBeFalse();expect(topographyMuseumContains(x-w.nx*.02,z-w.nz*.02)).toBeTrue();}});
 test("local terrain comes from city ground and exact site surfaces keep court/cellar holes",()=>{const sample=worldGroundSampler(vox);for(let x=702;x<962;x+=16)for(let z=1302;z<1466;z+=16)expect(topographySourceGroundAt(x,z)).toBe(sample(x,z));expect(topographySiteSurfaceAt(850,1380)).toBe(5.6);expect(topographySiteSurfaceAt(800,1380)).toBeNull();expect(topographySiteSurfaceAt(741,1423)).toBeNull();expect(topographyMuseumTopAt(800,1380)).toBeNull();expect(topographyMuseumTopAt(780,1380)).toBe(13.2);});
 test("water remains above actual city ground triangles across the courtyard",()=>{
  const palette=Object.fromEntries(vox.classes.map(c=>[c,[1,1,1]])),ground=createGroundSlabs(vox,"bounded source ground",palette,{skipAtWorld:(x,z)=>x<790||x>812||z<1368||z>1388}),detail=create(),root=new Group().add(ground,detail);root.updateMatrixWorld(true);
  for(let x=795;x<808;x+=2)for(let z=1373;z<1385;z+=2){const hits=new Raycaster(new Vector3(x,20,z),new Vector3(0,-1,0),0,25).intersectObject(root,true);expect(hits[0].object.name).toBe("Courtyard water mirror");expect(hits[0].point.y).toBeCloseTo(3.43,4);}
 });
 test("real source columns are removed only within exact replacement footprints and height bands",()=>{let owned=0;for(const[x,z,lo,hi]of rawCells){const source=S.prisms.some(p=>topographyPointInRing(p.ring,x*10,z*10));if(source&&hi-lo<=12){expect(topographySourceColumnContains(x,z,lo,hi,vox.cell_m)).toBeTrue();owned++;}}expect(owned).toBeGreaterThan(1000);expect(topographySourceColumnContains(850,1380,4.3,30)).toBeFalse();expect(topographySourceColumnContains(800,1360,3.4,19.4)).toBeFalse();expect(topographySourceColumnContains(690,1380,3.4,8.3)).toBeFalse();expect(topographySourceColumnContains(850,1380,4.3,8.3,0)).toBeFalse();});
 for(const minecraft of [false,true])for(const mobileLike of [false,true])test(`${minecraft?"Minecraft":"drawn"} ${mobileLike?"mobile":"full"} stays complete, finite and image-free`,()=>{const root=create({minecraft,mobileLike,diagnostics:true});let bytes=0,renderables=0;root.traverse(o=>{if(o instanceof Mesh){renderables++;for(const a of Object.values(o.geometry.attributes)){expect(Array.from(a.array).every(Number.isFinite)).toBeTrue();bytes+=a.array.byteLength;}bytes+=o.geometry.index?.array.byteLength??0;expect(o.geometry.getAttribute("uv")).toBeUndefined();if(o instanceof InstancedMesh){bytes+=o.instanceMatrix.array.byteLength+(o.instanceColor?.array.byteLength??0);expect(Array.from(o.instanceMatrix.array).every(Number.isFinite)).toBeTrue();expect((o.material as MeshBasicMaterial).vertexColors).toBeFalse();}expect(o.userData.nightMaterial).toBeDefined();}});expect(renderables).toBeLessThanOrEqual(11);expect(bytes).toBeLessThan(minecraft?410000:900000);for(const[role,n]of Object.entries({"2025 rooftop photovoltaic group":15,"mapped main entry stair":7,"trench protective glass canopy":72,"mapped cellar perimeter relief":6}))expect(root.userData.detailCounts[role]).toBe(n);expect(root.userData.geometryStatus).toContain("display estimates");});
 for(const minecraft of [false,true])test(`${minecraft?"Minecraft":"drawn"} actual roof rays keep the court open and every PV group visible`,()=>{const root=create({minecraft,diagnostics:true});root.updateMatrixWorld(true);const ray=(x:number,z:number)=>new Raycaster(new Vector3(x,20,z),new Vector3(0,-1,0),0,25).intersectObject(root,true);const court=ray(800,1380);expect(court[0].object.name).toBe("Courtyard water mirror");expect(court[0].point.y).toBeCloseTo(3.43,4);for(const b of(root.userData.blocks as TopographyBlock[]).filter(b=>b.role==="2025 rooftop photovoltaic group")){expect(topographyMuseumContains(b.position[0],b.position[2])).toBeTrue();expect(ray(b.position[0],b.position[2])[0].point.y).toBeGreaterThan(13.2);}});
 for(const mobileLike of [false,true])test(`Minecraft ${mobileLike?"mobile":"full"} actual facade stays visible over retained source voxels`,()=>{const detail=createMc({mobileLike,diagnostics:true}),root=new Group().add(sourceCells(),detail);root.updateMatrixWorld(true);let tested=0;for(const[i,b]of(detail.userData.blocks as TopographyBlock[]).filter(b=>b.role==="screen backing glazing").entries()){if(i%3)continue;const[nx,nz]=b.normal!,hit=new Raycaster(new Vector3(b.position[0]+nx*5,b.position[1],b.position[2]+nz*5),new Vector3(-nx,0,-nz),0,7).intersectObject(root,true)[0];expect(hit).toBeDefined();expect(hit.object.parent?.name).toBe(detail.name);tested++;}expect(tested).toBeGreaterThan(40);});
 test("collision follows actual authored solids while public approaches stay free",()=>{const solids=topographyAuthoredSolids();expect(solids.length).toBeGreaterThan(500);for(const s of solids.filter((_,i)=>i%31===0)){expect(topographyAuthoredSolidAt(s.x,s.z,s.y-.01,.02,0)).toBeTrue();expect(topographyAuthoredTopAt(s.x,s.z)).toBeGreaterThanOrEqual(s.y+s.height/2-.001);}for(const[x,z]of[[783.107,1337.936],[850,1340],[860,1380]])expect(topographyAuthoredSolidAt(x,z,topographySiteSurfaceAt(x,z)??4.6,1.8,.25)).toBeFalse();});
});
