export type Language = "de" | "en";

export const LANGUAGE_STORAGE_KEY = "isometric-berlin.language";

const DE = {
  actions: "Aktionen",
  alignMove: "Ausrichten & bewegen",
  attraction: "Sehenswürdigkeit",
  attractions: "Sehenswürdigkeiten",
  close: "Schließen",
  closeActions: "Aktionsmenü schließen",
  closeControls: "Steuerung schließen",
  closeHelp: "Hilfe schließen",
  closeReference: "Referenzkarte schließen",
  coach: "Kompass öffnet die Steuerung · Pfeil blendet sie aus",
  controls: "Kartensteuerung",
  copyLink: "Ansicht-Link kopieren",
  dataClose: "Datenquellen schließen",
  dataOpen: "Datenquellen und Status anzeigen",
  day: "Tag",
  eastUp: "Ost oben",
  flight: "Flugsteuerung",
  flyBack: "Rückwärts fliegen",
  flyForward: "Vorwärts fliegen",
  flyLeft: "Seitwärts nach links fliegen",
  flyRight: "Seitwärts nach rechts fliegen",
  focus: "Fokus",
  freelyRotated: "frei gedreht",
  help: "Hilfe",
  helpTitle: "Tastenkürzel & Bedienung",
  hideControls: "Bedienelemente ausblenden",
  home: "Gesamtansicht",
  language: "Sprache",
  link: "Link",
  loadingMap: "Lade hochauflösende Detailkarte",
  loadingMesh: "Lade amtliches 3D-Mesh",
  map: "Detailkarte",
  minecraft: "Minecraft",
  mode: "Modus",
  moreActions: "Weitere Aktionen",
  music: "Musik",
  musicOff: "Musik aus",
  musicOn: "Musik an",
  musicStarting: "Musik wird gestartet",
  next: "Weiter",
  nextAttraction: "Nächste Sehenswürdigkeit",
  night: "Nacht",
  northUp: "Nord oben",
  oppositeView: "Gegenansicht",
  orientation: "Kartenorientierung",
  previous: "Zurück",
  previousAttraction: "Vorige Sehenswürdigkeit",
  projectAndCurrent: "Projektname und aktuelle Sehenswürdigkeit",
  ready: "Bereit",
  reference: "Top-down Referenzkarte",
  repository: "Repo",
  reset: "Zurücksetzen",
  resetOrientation: "Ausrichtung zurücksetzen",
  roleAdded: "ergänzter Ort",
  roleHero: "Hauptmotiv",
  roleRequired: "Pflicht-Sehenswürdigkeit",
  rotateLeft: "Nach links drehen",
  rotateRight: "Nach rechts drehen",
  showAttractions: "Sehenswürdigkeiten ein- oder ausblenden",
  showControls: "Bedienelemente wieder einblenden",
  southUp: "Süd oben",
  startTour: "Sehenswürdigkeiten-Tour starten",
  stopTour: "Tour pausieren",
  threeD: "Freie 3D-Ansicht",
  tiltDown: "Kamera tiefer bis zur Untersicht neigen",
  tiltUp: "Kamera höher neigen",
  tour: "Tour",
  underside: "Untersicht",
  visualModes: "Darstellung: Tag, Nacht oder Minecraft",
  westUp: "West oben",
  zoomIn: "Vergrößern",
  zoomOut: "Verkleinern",
} as const;

type CopyKey = keyof typeof DE;

const EN: Record<CopyKey, string> = {
  actions: "Actions",
  alignMove: "Orient & move",
  attraction: "Sight",
  attractions: "Sights",
  close: "Close",
  closeActions: "Close actions",
  closeControls: "Close controls",
  closeHelp: "Close help",
  closeReference: "Close reference map",
  coach: "Compass opens controls · arrow hides them",
  controls: "Map controls",
  copyLink: "Copy view link",
  dataClose: "Close data sources",
  dataOpen: "Show data sources and status",
  day: "Day",
  eastUp: "East up",
  flight: "Flight controls",
  flyBack: "Fly backward",
  flyForward: "Fly forward",
  flyLeft: "Strafe left",
  flyRight: "Strafe right",
  focus: "Focus",
  freelyRotated: "freely rotated",
  help: "Help",
  helpTitle: "Keyboard & controls",
  hideControls: "Hide controls",
  home: "Overview",
  language: "Language",
  link: "Link",
  loadingMap: "Loading high-resolution detail map",
  loadingMesh: "Loading official 3D mesh",
  map: "Detail map",
  minecraft: "Minecraft",
  mode: "Mode",
  moreActions: "More actions",
  music: "Music",
  musicOff: "Music off",
  musicOn: "Music on",
  musicStarting: "Starting music",
  next: "Next",
  nextAttraction: "Next sight",
  night: "Night",
  northUp: "North up",
  oppositeView: "Opposite view",
  orientation: "Map orientation",
  previous: "Back",
  previousAttraction: "Previous sight",
  projectAndCurrent: "Project name and current sight",
  ready: "Ready",
  reference: "Top-down reference map",
  repository: "Repo",
  reset: "Reset",
  resetOrientation: "Reset orientation",
  roleAdded: "added place",
  roleHero: "hero subject",
  roleRequired: "required sight",
  rotateLeft: "Rotate left",
  rotateRight: "Rotate right",
  showAttractions: "Show or hide sights",
  showControls: "Show controls",
  southUp: "South up",
  startTour: "Start sights tour",
  stopTour: "Pause tour",
  threeD: "Free 3D view",
  tiltDown: "Tilt camera down into the underside view",
  tiltUp: "Tilt camera up",
  tour: "Tour",
  underside: "Underside",
  visualModes: "Appearance: day, night, or Minecraft",
  westUp: "West up",
  zoomIn: "Zoom in",
  zoomOut: "Zoom out",
};

export const UI_COPY: Record<Language, Record<CopyKey, string>> = {
  de: DE,
  en: EN,
};

export function initialLanguage(): Language {
  try {
    const requested = new URLSearchParams(window.location.search).get("lang");
    if (requested === "de" || requested === "en") {
      return requested;
    }
    const stored = window.localStorage.getItem(LANGUAGE_STORAGE_KEY);
    if (stored === "de" || stored === "en") {
      return stored;
    }
    return window.navigator.language.toLowerCase().startsWith("en") ? "en" : "de";
  } catch {
    return "de";
  }
}
