export type Language = "de" | "en";

export const LANGUAGE_STORAGE_KEY = "isometric-berlin.language";

const DE = {
  actions: "Aktionen",
  alignMove: "Ausrichten & bewegen",
  attraction: "Sehenswürdigkeit",
  attractions: "Sehenswürdigkeiten",
  close: "Schließen",
  closeActions: "Aktionsmenü schließen",
  closeControls: "Steuerung schließen",
  closeHelp: "Hilfe schließen",
  closeReference: "Referenzkarte schließen",
  coach: "Kompass öffnet die Steuerung · Pfeil blendet sie aus",
  controls: "Kartensteuerung",
  copyLink: "Ansicht-Link kopieren",
  dataClose: "Datenquellen schließen",
  dataOpen: "Datenquellen und Status anzeigen",
  day: "Tag",
  eastUp: "Ost oben",
  flight: "Flugsteuerung",
  flipHorizontal: "Horizontal spiegeln",
  flipVertical: "Vertikal klappen",
  flyBack: "Rückwärts fliegen",
  flyForward: "Vorwärts fliegen",
  flyLeft: "Seitwärts nach links fliegen",
  flyRight: "Seitwärts nach rechts fliegen",
  fullscreenEnter: "Vollbild öffnen",
  fullscreenExit: "Vollbild verlassen",
  focus: "Fokus",
  freelyRotated: "frei gedreht",
  help: "Hilfe",
  helpTitle: "Tastenkürzel & Bedienung",
  hideControls: "Bedienelemente ausblenden",
  home: "Gesamtansicht",
  language: "Sprache",
  link: "Link",
  loadingMap: "Lade hochauflösende Detailkarte",
  loadingMesh: "Lade amtliches 3D-Mesh",
  map: "Detailkarte",
  minecraft: "Minecraft",
  mode: "Modus",
  moreActions: "Weitere Aktionen",
  music: "Musik",
  musicOff: "Musik aus",
  musicOn: "Musik an",
  soundtrack: "Dusk Republic",
  soundtrackOff: "Soundtrack aus",
  soundtrackOn: "Soundtrack an (Dusk Republic)",
  soundtrackShortcut: "Dusk Republic an / aus",
  soundtrackWaiting: "Soundtrack wartet auf einen Klick (Autoplay blockiert)",
  musicStarting: "Musik wird gestartet",
  next: "Weiter",
  nextAttraction: "Nächste Sehenswürdigkeit",
  night: "Nacht",
  nightLightsOff: "Licht aus (Mondlicht)",
  nightLightsOn: "Licht an",
  northUp: "Nord oben",
  oppositeView: "Gegenansicht",
  orientation: "Kartenorientierung",
  pedestrian: "Spaziergang",
  pedestrianCanvas:
    "Spaziergänger-Ansicht auf 1,80 Meter Augenhöhe; ziehen zum Umschauen",
  pedestrianJump: "Springen",
  pedestrianOff: "Spaziergänger-Modus beendet",
  pedestrianOn: "Spaziergänger-Modus · Start am aktuellen Standort",
  previous: "Zurück",
  previousAttraction: "Vorige Sehenswürdigkeit",
  projectAndCurrent: "Projektname und aktuelle Sehenswürdigkeit",
  rain: "Regen",
  rainActive: "Regen eingeschaltet",
  rainInactive: "Regen ausgeschaltet",
  rainOff: "Regen ausschalten",
  rainOn: "Mittelstarken Regen einschalten",
  ready: "Bereit",
  reference: "Top-down Referenzkarte",
  repository: "Repo",
  reset: "Zurücksetzen",
  resetOrientation: "Ausrichtung zurücksetzen",
  resetView: "Standardansicht: Reichstag von der Wiese bei Tag",
  resetViewShort: "Standardansicht",
  roleAdded: "ergänzter Ort",
  roleHero: "Hauptmotiv",
  roleRequired: "Pflicht-Sehenswürdigkeit",
  rotateLeft: "Nach links drehen",
  rotateRight: "Nach rechts drehen",
  showAttractions: "Sehenswürdigkeiten ein- oder ausblenden",
  showControls: "Bedienelemente wieder einblenden",
  southUp: "Süd oben",
  snowfall: "Schneefall",
  snowfallActive: "Schneefall eingeschaltet",
  snowfallInactive: "Schneefall ausgeschaltet",
  snowfallOff: "Schneefall ausschalten",
  snowfallOn: "Schneefall einschalten",
  snowstorm: "Schneesturm",
  startTour: "Sehenswürdigkeiten-Tour starten",
  stopTour: "Tour pausieren",
  switchToMap: "Zur hochauflösenden Kartenansicht wechseln",
  switchToThreeD: "Zur freien amtlichen 3D-Ansicht wechseln",
  threeD: "Freie 3D-Ansicht",
  tiltDown: "Kamera tiefer bis zur Untersicht neigen",
  tiltUp: "Kamera höher neigen",
  tour: "Tour",
  trueUnderside: "Untergrundübersicht mit Bahn- und Tiergartentunneln",
  underside: "Untersicht",
  viewTransform: "Ansicht drehen und umklappen",
  visualModes: "Darstellung: Tag, Nacht, Minecraft oder Schneesturm",
  westUp: "West oben",
  zoomIn: "Vergrößern",
  zoomOut: "Verkleinern",
} as const;

type CopyKey = keyof typeof DE;

const EN: Record<CopyKey, string> = {
  actions: "Actions",
  alignMove: "Orient & move",
  attraction: "Sight",
  attractions: "Sights",
  close: "Close",
  closeActions: "Close actions",
  closeControls: "Close controls",
  closeHelp: "Close help",
  closeReference: "Close reference map",
  coach: "Compass opens controls · arrow hides them",
  controls: "Map controls",
  copyLink: "Copy view link",
  dataClose: "Close data sources",
  dataOpen: "Show data sources and status",
  day: "Day",
  eastUp: "East up",
  flight: "Flight controls",
  flipHorizontal: "Mirror horizontally",
  flipVertical: "Flip vertically",
  flyBack: "Fly backward",
  flyForward: "Fly forward",
  flyLeft: "Strafe left",
  flyRight: "Strafe right",
  fullscreenEnter: "Enter fullscreen",
  fullscreenExit: "Exit fullscreen",
  focus: "Focus",
  freelyRotated: "freely rotated",
  help: "Help",
  helpTitle: "Keyboard & controls",
  hideControls: "Hide controls",
  home: "Overview",
  language: "Language",
  link: "Link",
  loadingMap: "Loading high-resolution detail map",
  loadingMesh: "Loading official 3D mesh",
  map: "Detail map",
  minecraft: "Minecraft",
  mode: "Mode",
  moreActions: "More actions",
  music: "Music",
  musicOff: "Music off",
  musicOn: "Music on",
  soundtrack: "Dusk Republic",
  soundtrackOff: "Soundtrack off",
  soundtrackOn: "Soundtrack on (Dusk Republic)",
  soundtrackShortcut: "Toggle Dusk Republic",
  soundtrackWaiting: "Soundtrack waiting for a click (autoplay blocked)",
  musicStarting: "Starting music",
  next: "Next",
  nextAttraction: "Next sight",
  night: "Night",
  nightLightsOff: "Lights off (moonlight)",
  nightLightsOn: "Lights on",
  northUp: "North up",
  oppositeView: "Opposite view",
  orientation: "Map orientation",
  pedestrian: "Walk",
  pedestrianCanvas:
    "Pedestrian view at 1.80 metre eye height; drag to look around",
  pedestrianJump: "Jump",
  pedestrianOff: "Pedestrian mode off",
  pedestrianOn: "Pedestrian mode · start at current location",
  previous: "Back",
  previousAttraction: "Previous sight",
  projectAndCurrent: "Project name and current sight",
  rain: "Rain",
  rainActive: "Rain on",
  rainInactive: "Rain off",
  rainOff: "Turn rain off",
  rainOn: "Turn moderate rain on",
  ready: "Ready",
  reference: "Top-down reference map",
  repository: "Repo",
  reset: "Reset",
  resetOrientation: "Reset orientation",
  resetView: "Default view: Reichstag from the lawn in daylight",
  resetViewShort: "Default view",
  roleAdded: "added place",
  roleHero: "hero subject",
  roleRequired: "required sight",
  rotateLeft: "Rotate left",
  rotateRight: "Rotate right",
  showAttractions: "Show or hide sights",
  showControls: "Show controls",
  southUp: "South up",
  snowfall: "Snowfall",
  snowfallActive: "Snowfall on",
  snowfallInactive: "Snowfall off",
  snowfallOff: "Turn snowfall off",
  snowfallOn: "Turn snowfall on",
  snowstorm: "Snowstorm",
  startTour: "Start sights tour",
  stopTour: "Pause tour",
  switchToMap: "Switch to the high-resolution detail map",
  switchToThreeD: "Switch to the free official 3D view",
  threeD: "Free 3D view",
  tiltDown: "Tilt camera down into the underside view",
  tiltUp: "Tilt camera up",
  tour: "Tour",
  trueUnderside: "Underground overview with rail and Tiergarten tunnels",
  underside: "Underside",
  viewTransform: "Rotate and flip view",
  visualModes: "Appearance: day, night, Minecraft, or snowstorm",
  westUp: "West up",
  zoomIn: "Zoom in",
  zoomOut: "Zoom out",
};

export const UI_COPY: Record<Language, Record<CopyKey, string>> = {
  de: DE,
  en: EN,
};

export function initialLanguage(): Language {
  try {
    const requested = new URLSearchParams(window.location.search).get("lang");
    if (requested === "de" || requested === "en") {
      return requested;
    }
    const stored = window.localStorage.getItem(LANGUAGE_STORAGE_KEY);
    if (stored === "de" || stored === "en") {
      return stored;
    }
    return window.navigator.language.toLowerCase().startsWith("en")
      ? "en"
      : "de";
  } catch {
    return "de";
  }
}
