import {
  BoxGeometry,
  Color,
  DoubleSide,
  Group,
  InstancedMesh,
  Matrix4,
  MeshBasicMaterial,
  PlaneGeometry,
  Vector3,
  MeshStandardMaterial,
} from "three";

import { isHolocaustMinecraftProtectedAt } from "./holocaustField";

import {
  MATERIAL_PALETTES,
  MINECRAFT_BUILDING_PALETTE,
} from "./visual-modes/minecraft/palette";
import {
  BERLIN_MODERN_PROFILE,
  EUROPACITY_PROFILE,
  KOLLHOFF_TOWER_PROFILE,
  NORTHERN_CITY_PROFILE,
  RIECKHALLEN_PROFILE,
} from "./expandedCityProfiles";
import { isChancelleryExtensionConstructionPoint } from "./chancelleryExtensionProfile";
import { createMinecraftHistoricParkBridges } from "./MinecraftHistoricParkBridges";
import { createMinecraftHumboldthafenDetails } from "./MinecraftHumboldthafen";
import {
  SIEGESSAEULE_BRONZE_TONES,
  SIEGESSAEULE_MOSAIC_TONES,
  SIEGESSAEULE_PROFILE,
} from "./SiegessaeuleProfile";
import {
  MINECRAFT_ARCHITECTURAL_PROFILES,
  createMinecraftArchitecturalLandmarks,
  isMinecraftArchitecturalReplacementColumn,
  minecraftArchitecturalVoxelTopAt,
} from "./MinecraftArchitecturalLandmarks";
import { createMinecraftInvalidenfriedhofDetails } from "./InvalidenfriedhofDetails";
import { createMinecraftBrechtMemorial } from "./BerlinerEnsembleMemorials";
import { createMinecraftPariserPlatzArchitecture } from "./MinecraftPariserPlatzArchitecture";
import { createTiergartenLiteraryMemorialsMinecraft } from "./TiergartenLiteraryMemorials";
import {
  createWagnerMemorialMinecraft,
  wagnerMemorialVoxelReplacementAt,
} from "./WagnerMemorial";
import { createMoabitPrisonMemorialParkMinecraft } from "./MoabitPrisonMemorialPark";
import { createWeidendammerBridgeMinecraft } from "./WeidendammerBridgeDetails";
import {
  SOCIAL_COURT_PROFILE,
  socialCourtFacadeWorldAt,
} from "./SocialCourtDetails";
import {
  createMinecraftTipiAmKanzleramt,
  isMinecraftTipiReplacementColumn,
} from "./MinecraftTipiAmKanzleramt";
import { isNorthernHumboldthafenReplacementCell } from "./HumboldthafenSources";
import {
  AXIS_FROM,
  AXIS_TO,
  DATA_EAST_M,
  EXTRAPOLATED_MARGIN_M,
  PRESENTATION_FLOOR_Y_M,
  VISIBLE_RADIUS_M,
  extrapolatedEnvelopeBounds,
  extrapolatedMarginBands,
} from "./worldEnvelope";
import {
  createTunnelPortalApproachTester,
  type TunnelPortalCourseInput,
} from "./TunnelPortals";

/**
 * True voxel world for the Minecraft mode: the city as axis-aligned
 * blocks generated by `isometric_berlin.generation.build_minecraft_voxels`
 * from surveyed LoD2 footprints + measured heights, OSM water/roads and
 * the official tree points. Rendered as a handful of InstancedMeshes
 * (one box per building column / ground run / tree part) so the whole
 * world stays at a few draw calls and well below photogrammetry-tier
 * triangle counts — deliberately "eckig, klotzig, blockig".
 */
export type VoxelPayload = {
  schema_version: number;
  cell_m: number;
  classes: string[];
  grid: { cols: number; min_x_idx: number; min_z_idx: number; rows: number };
  /** Coarse ground-top heights in decimetres, row-major at stride_cells. */
  ground_height: {
    cols: number;
    rows: number;
    stride_cells: number;
    y_dm: number[];
  };
  /** rows[z_offset] = [x_start_offset, run_length, classId][] (grid offsets). */
  ground_rows: Array<Array<[number, number, number]>>;
  /** Legacy schema 1: absolute [x_idx, z_idx, y0_dm, y1_dm, classId]. */
  buildings?: VoxelBuildingColumn[];
  /** Schema 2: rows[z_offset] = [x_offset, run, y0_dm, y1_dm, classId][]. */
  building_rows?: Array<Array<[number, number, number, number, number]>>;
  /** Legacy schema 1: absolute [x_idx, z_idx, y0_dm, height_dm]. */
  trees?: VoxelTreeBlock[];
  /** Schema 2: rows[z_offset] = [x_offset, y0_dm, height_dm][]. */
  tree_rows?: Array<Array<[number, number, number]>>;
  water_top_y_m: number;
};

export type MinecraftVoxelDetailProfile = "full" | "mobile";

export type MinecraftVoxelWorldOptions = {
  /**
   * `mobile` keeps the surveyed envelopes and authored landmarks while
   * dropping city-wide decorative micro-detail and redundant generic layers.
   * Omitted means `full`, preserving the existing desktop output exactly.
   */
  detailProfile?: MinecraftVoxelDetailProfile;
};

export type VoxelBuildingColumn = [number, number, number, number, number];
export type VoxelTreeBlock = [number, number, number, number];

/** Losslessly expand the compact schema-2 rows, while accepting schema 1. */
export function decodeVoxelBuildingColumns(
  payload: VoxelPayload,
): VoxelBuildingColumn[] {
  if (!payload.building_rows) return payload.buildings ?? [];
  const columns: VoxelBuildingColumn[] = [];
  payload.building_rows.forEach((row, zOffset) => {
    for (const [xOffset, runLength, y0dm, y1dm, classId] of row) {
      for (let offset = 0; offset < runLength; offset += 1) {
        columns.push([
          payload.grid.min_x_idx + xOffset + offset,
          payload.grid.min_z_idx + zOffset,
          y0dm,
          y1dm,
          classId,
        ]);
      }
    }
  });
  return columns;
}

/** Losslessly expand compact schema-2 trees, while accepting schema 1. */
export function decodeVoxelTreeBlocks(payload: VoxelPayload): VoxelTreeBlock[] {
  if (!payload.tree_rows) return payload.trees ?? [];
  const trees: VoxelTreeBlock[] = [];
  payload.tree_rows.forEach((row, zOffset) => {
    for (const [xOffset, y0dm, heightDm] of row) {
      trees.push([
        payload.grid.min_x_idx + xOffset,
        payload.grid.min_z_idx + zOffset,
        y0dm,
        heightDm,
      ]);
    }
  });
  return trees;
}

export const VOXEL_WORLD_FILE = "minecraft-voxels.json";
/** Terrain-only sibling used by Day/Night/Snow/Schwellenraum on first load. */
export const GROUND_CONTEXT_FILE = "ground-context.json";
const GROUND_SLAB_M = 3;
/**
 * Spree/Kanal water table (fallback for payloads without the field).
 * The banks sit at ~4.2 m, so the river runs in a real cut about 5.3 m
 * below the city instead of level with the streets.
 */
export const WATER_TOP_Y = -1.15;

// Every shade comes from MINECRAFT_PALETTE (palette.ts); small
// deterministic per-instance jitter between shades is what gives the
// classic Minecraft block-noise without any texture.
// Owner note "bessere Farben im Minecraft mode": each class now uses
// two or three CLOSE shades (gentle block-noise instead of the harsh
// checkerboard), greens follow classic plains grass/oak leaves, water is
// the clear Minecraft blue and roads read as dark slate, not void-black.
const CLASS_SHADES: Record<string, readonly number[]> = {
  asphalt: [0x40515c, 0x34443a],
  concrete: [0xd4d4b7, 0xf3efd0],
  glass: [0x72c5d2, 0xa4dfe2],
  grass: [0x74b043, 0x5d9634, 0x74b043],
  plazaBrick: [0x994a35, 0x715b4a],
  // A constructed basin is the same blue as the river, but its cells keep
  // the local ground height instead of the Spree table — an ornamental
  // basin sits on the ground it was built into, not 6 m below it.
  basin: [0x3f76e4, 0x2e5aa8],
  // Tiergarten ponds/streams use the same calm block-water palette while
  // remaining on their local park terrain instead of the lower Spree table.
  pond: [0x4b8fc4, 0x3576a8],
  // Bridge decks over the Spree/Humboldthafen read as stone blocks.
  bridge: [0x8e9a9e, 0xa4aa91],
  sandstone: [0xe8d1ae, 0xf5e3c5],
  // Bare concrete for freestanding walls: no interior, so no windows.
  wall: [0xb8b4a8, 0xc7c3b6],
  water: [0x3f76e4, 0x2e5aa8],
};
/** Column classes that are solid structures rather than inhabited floors. */
const WINDOWLESS_CLASSES: ReadonlySet<string> = new Set(["wall"]);
const FALLBACK_SHADES: readonly number[] = CLASS_SHADES.concrete;
const TRUNK_SHADES: readonly number[] = [0x704a2d];
const LEAF_SHADES: readonly number[] = [0x4c7f28, 0x5d9634];
// Facade window cells read as MINECRAFT GLASS — light, glassy blocks
// from the master palette. The former dark slate (0x40515c) punched
// black holes into every facade ("hässliche schwarze Fenster").
const VOXEL_WINDOW_GLASS = 0xa4dfe2;
const VOXEL_WINDOW_GLASS_PALE = 0xd6dfe0;
const VOXEL_WINDOW_TEAL = 0x72c5d2;
const KOLLHOFF_TOWER_PAYLOAD_IDS: ReadonlySet<string> = new Set(
  KOLLHOFF_TOWER_PROFILE.payloadIds,
);
export const VOXEL_WINDOW_WIDTH_M = 1.5;
export const VOXEL_WINDOW_HEIGHT_M = 2.75;

/**
 * The memorial clearing was rasterised into 86 four-metre "building" columns
 * in the voxel payload. This documented 60 m artwork is open landscape, so the
 * low false-positive mass must yield to the dedicated recognition model.
 */
export const SINTI_ROMA_VOXEL_CLEARING = {
  center: [307.7, 186.23] as const,
  halfDepthM: 38,
  halfWidthM: 22,
  maxFalseHeightM: 4.1,
} as const;

export function isFalseSintiRomaVoxelColumn(
  worldX: number,
  worldZ: number,
  heightM: number,
): boolean {
  return (
    heightM <= SINTI_ROMA_VOXEL_CLEARING.maxFalseHeightM &&
    Math.abs(worldX - SINTI_ROMA_VOXEL_CLEARING.center[0]) <=
      SINTI_ROMA_VOXEL_CLEARING.halfWidthM &&
    Math.abs(worldZ - SINTI_ROMA_VOXEL_CLEARING.center[1]) <=
      SINTI_ROMA_VOXEL_CLEARING.halfDepthM
  );
}

/**
 * LoD2 part DEBE01YYK0001zDa is a valid bridge envelope, but voxelising its
 * footprint from terrain to the 28.7 m top turns it into a closed wall over
 * the Spree. The always-visible central recognition layer supplies both open
 * bridge levels, so only the narrow source-prism corridor yields here.
 */
export const BUNDESTAG_SPREE_BRIDGE_VOXEL_CLEARING = {
  // Exact world bounds of LoD2 part DEBE01YYK0001zDa. Using the former
  // coarse 310…378 m box also erased three 32 m connector-building columns.
  maxX: 375.424,
  maxZ: -179.962,
  minFalseHeightM: 20,
  minX: 312.831,
  minZ: -184.3,
  sourceBuildingId: "DEBE01YYK0001zDa",
} as const;

export function isFalseBundestagSpreeBridgeVoxelColumn(
  worldX: number,
  worldZ: number,
  heightM: number,
): boolean {
  const clearing = BUNDESTAG_SPREE_BRIDGE_VOXEL_CLEARING;
  return (
    heightM >= clearing.minFalseHeightM &&
    worldX >= clearing.minX &&
    worldX <= clearing.maxX &&
    worldZ >= clearing.minZ &&
    worldZ <= clearing.maxZ
  );
}

/** Eleven block-deck cells beneath the always-visible lower civic footbridge. */
export const BUNDESTAG_SPREE_BRIDGE_GROUND_CLEARING = {
  maxX: 364,
  maxZ: -184,
  minX: 320,
  minZ: -188,
  osmWayId: "30596778",
} as const;

export function isBundestagSpreeBridgeGroundCell(
  worldX: number,
  worldZ: number,
): boolean {
  const clearing = BUNDESTAG_SPREE_BRIDGE_GROUND_CLEARING;
  return (
    worldX >= clearing.minX &&
    worldX <= clearing.maxX &&
    worldZ >= clearing.minZ &&
    worldZ <= clearing.maxZ
  );
}

/** LoD2-tower-derived centre of the Hamburger Bahnhof entrance facade. */
export const HAMBURGER_BAHNHOF_VOXEL_FACADE = {
  axis: [0.8673, -0.4978] as const,
  center: [72.855, -1043.07] as const,
  groundY: 8,
  normal: [0.4978, 0.8673] as const,
  rotationDegrees: 30,
} as const;

export type VoxelRecognitionArea = {
  center: readonly [number, number];
  depthM: number;
  name: string;
  paddingM: number;
  rotationDegrees: number;
  tone: number;
  widthM: number;
};

// Metric envelopes copied from the versioned architectural signatures in
// scene.json. The true voxel columns remain untouched; only their generic
// square-window overlay yields to the more accurate recognition model.
const RECOGNITION_AREAS: readonly VoxelRecognitionArea[] = [
  {
    center: [317.729, 40.477],
    depthM: 138,
    name: "Reichstag",
    paddingM: 10,
    rotationDegrees: -1.676,
    tone: 0xd4d4b7,
    widthM: 100,
  },
  {
    center: [-220.236, -145.806],
    depthM: 102.074,
    name: "Bundeskanzleramt",
    paddingM: 6,
    rotationDegrees: -1.337,
    // Pale cool concrete, not the warm cream 0xf3efd0 this pin used to
    // carry. Cream has 31 units more green than blue, and once the voxel
    // rig multiplied it the Chancellery — white concrete in reality —
    // rendered as a khaki-yellow block across its whole 343 m envelope.
    tone: 0xd6dfe0,
    widthM: 342.676,
  },
  {
    center: [-119.936, -683.307],
    depthM: 200,
    name: "Berlin Hauptbahnhof",
    paddingM: 6,
    rotationDegrees: 21.82,
    tone: 0xd6dfe0,
    widthM: 341,
  },
  {
    // Paul-Löbe-Haus main parliamentary bar. Its block-native west grid and
    // committee rotundas own the fenestration; keep generic square panes out.
    center: [233.35, -135.15],
    depthM: 39.5,
    name: "Paul-Löbe-Haus main bar",
    paddingM: 2,
    rotationDegrees: 1.35,
    tone: 0xd6dfe0,
    widthM: 160,
  },
  {
    // Exact narrow west wing / canopy carrier (LoD2 HA7mKuzG).
    center: [143.5, -137.25],
    depthM: 105,
    name: "Paul-Löbe-Haus west wing",
    paddingM: 2,
    rotationDegrees: 0,
    tone: 0xd6dfe0,
    widthM: 31,
  },
  {
    // The two rows of committee-room rotundas project beyond the main bar.
    // Their curved block shells own the nearby panes as well as their source
    // cells; a bar-only rectangle leaves square generic windows through them.
    center: [233.35, -108.2],
    depthM: 22,
    name: "Paul-Löbe-Haus north rotundas",
    paddingM: 2,
    rotationDegrees: 0,
    tone: 0xd6dfe0,
    widthM: 132,
  },
  {
    center: [234, -161.8],
    depthM: 22,
    name: "Paul-Löbe-Haus south rotundas",
    paddingM: 2,
    rotationDegrees: 0,
    tone: 0xd6dfe0,
    widthM: 132,
  },
  {
    // MELH rotunda and Spree facade are authored as one block-native ensemble.
    center: [406, -139],
    depthM: 116,
    name: "Marie-Elisabeth-Lüders-Haus",
    paddingM: 2,
    rotationDegrees: 0,
    tone: 0xd6dfe0,
    widthM: 64,
  },
  {
    // The head building is not a generic office facade. A dedicated stepped
    // voxel elevation below carries its two towers and arched hall front.
    center: HAMBURGER_BAHNHOF_VOXEL_FACADE.center,
    depthM: 8,
    name: "Hamburger Bahnhof",
    paddingM: 2,
    rotationDegrees: HAMBURGER_BAHNHOF_VOXEL_FACADE.rotationDegrees,
    tone: 0xe8d1ae,
    widthM: 64,
  },
  {
    // Only the public Invalidenstrasse edge yields its generic office-window
    // grid. The deep LoD2 footprint, all three courtyards and every rear wing
    // remain source voxels behind the block-native 11-axis facade.
    center: SOCIAL_COURT_PROFILE.frontCenterWorldM,
    depthM: 12,
    name: "Sozialgericht Berlin",
    paddingM: 1.2,
    rotationDegrees: (SOCIAL_COURT_PROFILE.facade.rotationY * 180) / Math.PI,
    tone: 0xe8d1ae,
    widthM: SOCIAL_COURT_PROFILE.facade.facadeLengthM,
  },
  {
    center: EUROPACITY_PROFILE.einz.centerWorldM,
    depthM: EUROPACITY_PROFILE.einz.footprintDepthM,
    name: "KPMG Europacity",
    paddingM: 1,
    rotationDegrees: (EUROPACITY_PROFILE.einz.rotationY * 180) / Math.PI,
    tone: 0x789da4,
    widthM: EUROPACITY_PROFILE.einz.footprintLengthM,
  },
  {
    // One low 281 m freight hall, not a row of alternating 8/12 m voxel
    // peaks. The payload remains the footprint authority; this envelope only
    // evens the coarse top row and suppresses generic office windows.
    center: RIECKHALLEN_PROFILE.centerWorldM,
    depthM: RIECKHALLEN_PROFILE.lengthM,
    name: "Rieckhallen",
    paddingM: 0.6,
    rotationDegrees: (RIECKHALLEN_PROFILE.rotationY * 180) / Math.PI,
    tone: 0x586b6f,
    widthM: RIECKHALLEN_PROFILE.widthM,
  },
  {
    center: BERLIN_MODERN_PROFILE.centerWorldM,
    depthM: BERLIN_MODERN_PROFILE.footprintLengthM,
    name: "berlin modern",
    paddingM: 1,
    rotationDegrees: (BERLIN_MODERN_PROFILE.rotationY * 180) / Math.PI,
    tone: 0xe8d1ae,
    widthM: BERLIN_MODERN_PROFILE.footprintWidthM,
  },
  {
    center: [417.898, 300.453],
    depthM: 18,
    name: "Brandenburger Tor",
    paddingM: 3,
    rotationDegrees: 5.083,
    tone: 0xe8d1ae,
    widthM: 68,
  },
  {
    // Only the shallow north facade authored by the seventh architecture
    // batch yields its generic square windows. K00006ot's complete southern
    // hotel block remains measured voxel mass, including all courtyards.
    center: MINECRAFT_ARCHITECTURAL_PROFILES.hotelAdlon.front.centerWorldM,
    depthM: 2.4,
    name: "Hotel Adlon authored north facade",
    paddingM: 0.35,
    rotationDegrees:
      (MINECRAFT_ARCHITECTURAL_PROFILES.hotelAdlon.front.rotationY * 180) /
      Math.PI,
    tone: 0xf3efd0,
    widthM: MINECRAFT_ARCHITECTURAL_PROFILES.hotelAdlon.front.lengthM,
  },
  ...Object.values(
    MINECRAFT_ARCHITECTURAL_PROFILES.starbucksPariserPlatz.facades,
  ).map((facade): VoxelRecognitionArea => ({
    // The two tenant spans form a short L at K00005Hq's south-west corner.
    // Suppression is facade-thin; the parent office mass is never replaced.
    center: [
      facade.sourceStartWorldM[0] +
        facade.directionWorld[0] * facade.storefrontLengthM * 0.5,
      facade.sourceStartWorldM[1] +
        facade.directionWorld[1] * facade.storefrontLengthM * 0.5,
    ],
    depthM: 2.2,
    name: `Starbucks authored ${facade.key} facade`,
    paddingM: 0.3,
    rotationDegrees: (facade.rotationYRadians * 180) / Math.PI,
    tone: 0xd4d4b7,
    widthM: facade.storefrontLengthM,
  })),
  {
    // OSM way/1535591727. The exact bent outline is supplied by the
    // always-visible recognition model; suppress the generic square-window
    // overlay across its bbox so Minecraft does not put a second rectangular
    // office through the coloured 2026 facade.
    center: [-300.31, -359.65],
    depthM: 73.72,
    name: "Amtssitz am Spreebogen",
    paddingM: 4,
    rotationDegrees: 0,
    tone: 0xbba087,
    widthM: 92.9,
  },
];

export function voxelRecognitionAreaAt(
  x: number,
  z: number,
): VoxelRecognitionArea | null {
  for (const area of RECOGNITION_AREAS) {
    const radians = (area.rotationDegrees * Math.PI) / 180;
    const cosine = Math.cos(radians);
    const sine = Math.sin(radians);
    const dx = x - area.center[0];
    const dz = z - area.center[1];
    const localX = dx * cosine - dz * sine;
    const localZ = dx * sine + dz * cosine;
    if (
      Math.abs(localX) <= area.widthM / 2 + area.paddingM &&
      Math.abs(localZ) <= area.depthM / 2 + area.paddingM
    ) {
      return area;
    }
  }
  return null;
}

/**
 * Important retained source masses must read as stacked blocks too. Their
 * dedicated recognition models already own the silhouette and openings, but
 * Reichstag, Chancellery and the parliamentary bars intentionally retain
 * parts of their surveyed LoD2 mass underneath. Splitting only these areas
 * avoids turning the entire 4 km city into millions of extra instances.
 */
const MINECRAFT_HERO_COURSE_AREAS = new Set([
  "Reichstag",
  "Bundeskanzleramt",
  "Berlin Hauptbahnhof",
  "Paul-Löbe-Haus main bar",
  "Paul-Löbe-Haus west wing",
  "Paul-Löbe-Haus north rotundas",
  "Paul-Löbe-Haus south rotundas",
  "Marie-Elisabeth-Lüders-Haus",
  "Brandenburger Tor",
  "Sozialgericht Berlin",
]);

export const MINECRAFT_HERO_SOURCE_COURSE_MAX_M = 8;

function isMinecraftHeroSourceCourseArea(
  area: VoxelRecognitionArea | null,
): boolean {
  return area !== null && MINECRAFT_HERO_COURSE_AREAS.has(area.name);
}

export function isMinecraftHeroSourceCourseAreaAt(
  x: number,
  z: number,
): boolean {
  return isMinecraftHeroSourceCourseArea(voxelRecognitionAreaAt(x, z));
}

/**
 * Complete recognition components replace their coarse voxel mass rather than
 * sitting hidden inside it. This is intentionally narrower than the generic
 * recognition-area window suppression and preserves courtyards/neighbours.
 */
export function isCompleteRecognitionVoxelColumn(
  x: number,
  z: number,
): boolean {
  return (
    isMinecraftArchitecturalReplacementColumn(x, z) ||
    isMinecraftTipiReplacementColumn(x, z)
  );
}

function shadeFor(
  shades: readonly number[],
  xIdx: number,
  zIdx: number,
  salt: number,
): Color {
  const pick = Math.abs(xIdx * 31 + zIdx * 17 + salt * 7) % shades.length;
  return new Color(shades[pick]);
}

export function minecraftBuildingLayerTones(materialClass: string): {
  cap: number;
  plinth: number;
} {
  const warm = materialClass === "clinker" || materialClass === "plazaBrick";
  const glassy = materialClass === "glass";
  return {
    cap: warm
      ? MATERIAL_PALETTES.clinker[0]
      : glassy
        ? MATERIAL_PALETTES.metal[1]
        : MATERIAL_PALETTES.roofCopper[1],
    plinth: warm
      ? MATERIAL_PALETTES.clinker[1]
      : glassy
        ? MATERIAL_PALETTES.metal[0]
        : MATERIAL_PALETTES.sandstone[0],
  };
}

function voxelMaterial(emissive = 0x3d3d3d): MeshStandardMaterial {
  return new MeshStandardMaterial({
    color: 0xffffff,
    // A small neutral emissive floor lifts the shadow faces so block
    // colours stay readable all around, like Minecraft's flat light.
    // The drawn city passes 0 — its ground must not self-glow.
    emissive,
    flatShading: true,
    metalness: 0,
    roughness: 1,
  });
}

type InstanceWriter = {
  mesh: InstancedMesh;
  write: (
    center: Vector3,
    size: Vector3,
    color: Color,
    rotationY?: number,
  ) => void;
};

function instancedBoxes(
  name: string,
  count: number,
  emissive?: number,
): InstanceWriter {
  const mesh = new InstancedMesh(
    new BoxGeometry(1, 1, 1),
    voxelMaterial(emissive),
    Math.max(1, count),
  );
  mesh.name = name;
  mesh.count = 0;
  const matrix = new Matrix4();
  return {
    mesh,
    write: (center, size, color, rotationY = 0) => {
      const index = mesh.count;
      if (rotationY === 0) {
        matrix.makeScale(size.x, size.y, size.z);
      } else {
        matrix.makeRotationY(rotationY);
        matrix.scale(size);
      }
      matrix.setPosition(center.x, center.y, center.z);
      mesh.setMatrixAt(index, matrix);
      mesh.setColorAt(index, color);
      mesh.count = index + 1;
    },
  };
}

/**
 * Sample the payload's coarse interpolated terrain grid at grid offsets.
 */
export function groundTopSampler(
  payload: VoxelPayload,
): (xOffset: number, zOffset: number) => number {
  const heights = payload.ground_height;
  return (xOffset, zOffset) => {
    const col = Math.min(
      heights.cols - 1,
      Math.floor(xOffset / heights.stride_cells),
    );
    const row = Math.min(
      heights.rows - 1,
      Math.floor(zOffset / heights.stride_cells),
    );
    return (heights.y_dm[row * heights.cols + col] ?? 40) / 10;
  };
}

/**
 * Continuous counterpart to {@link groundTopSampler} for drawn surfaces.
 *
 * The committed height samples sit at the centres of 16 m terrain cells.
 * Nearest-cell lookup is correct for Minecraft blocks, but it made a road or
 * lawn jump vertically at every cell boundary. Bilinear interpolation keeps
 * the same measured samples and extrema while producing a continuous grade
 * for the isometric plates, kerbs and quay coping.
 */
export function smoothGroundTopSampler(
  payload: VoxelPayload,
): (xOffset: number, zOffset: number) => number {
  const heights = payload.ground_height;
  const valueAt = (col: number, row: number): number =>
    (heights.y_dm[row * heights.cols + col] ?? 40) / 10;
  return (xOffset, zOffset) => {
    const sampleX = xOffset / heights.stride_cells - 0.5;
    const sampleZ = zOffset / heights.stride_cells - 0.5;
    const rawCol = Math.floor(sampleX);
    const rawRow = Math.floor(sampleZ);
    const col0 = Math.max(0, Math.min(heights.cols - 1, rawCol));
    const row0 = Math.max(0, Math.min(heights.rows - 1, rawRow));
    const col1 = Math.max(0, Math.min(heights.cols - 1, rawCol + 1));
    const row1 = Math.max(0, Math.min(heights.rows - 1, rawRow + 1));
    const tx = col0 === col1 ? 0 : Math.max(0, Math.min(1, sampleX - rawCol));
    const tz = row0 === row1 ? 0 : Math.max(0, Math.min(1, sampleZ - rawRow));
    const north = valueAt(col0, row0) * (1 - tx) + valueAt(col1, row0) * tx;
    const south = valueAt(col0, row1) * (1 - tx) + valueAt(col1, row1) * tx;
    return north * (1 - tz) + south * tz;
  };
}

/**
 * Per-column real-colour lookup: point-in-footprint against the LoD2
 * prism payload, each building's sampled tone snapped to the nearest
 * Minecraft palette entry. Kills the one-colour-city ("einfarbig")
 * while staying strictly inside the authored block palette.
 */
export type ColumnToneLookup = (x: number, z: number) => number | null;

type TonedPrism = {
  hex: number;
  maxX: number;
  maxZ: number;
  minX: number;
  minZ: number;
  ring: Array<[number, number]>;
};

export function buildColumnToneLookup(prisms: {
  buildings: Array<{
    id?: string;
    ring: number[][];
    tone?: [number, number, number];
  }>;
}): ColumnToneLookup {
  // Chroma carries identity, brightness does not. Plain RGB distance let a
  // near-neutral concrete sample land on the sandstone creams simply
  // because they are the brightest entries — which is why the Chancellery,
  // white concrete in reality, rendered as a khaki-yellow block. Matching
  // on (luma, r−luma, b−luma) with the two chroma axes weighted four times
  // keeps a grey building grey and a warm building warm.
  const CHROMA_WEIGHT = 4;
  const luminance = (r: number, g: number, b: number): number =>
    0.2126 * r + 0.7152 * g + 0.0722 * b;
  const palette = MINECRAFT_BUILDING_PALETTE.map((hex) => {
    const r = (hex >> 16) & 255;
    const g = (hex >> 8) & 255;
    const b = hex & 255;
    const y = luminance(r, g, b);
    return { b, cb: b - y, cr: r - y, g, hex, r, y };
  });
  const snap = (tone: [number, number, number]): number => {
    // Lighten and desaturate the raw photo sample toward the drawn
    // city's bright band BEFORE matching ("heller"), so a building that
    // is pale cream by day is not a dark block in Minecraft.
    const luma = luminance(tone[0], tone[1], tone[2]);
    // Bright band, matching the drawn city's ivory register: the old floor
    // of 150 left most Berlin samples (median luma 111) sitting on the two
    // darkest stone entries, which is the grey-city look the owner rejected.
    const target = Math.min(236, Math.max(168, luma));
    const scale = target / Math.max(luma, 1);
    const lifted: [number, number, number] = [
      Math.min(255, tone[0] * scale),
      Math.min(255, tone[1] * scale),
      Math.min(255, tone[2] * scale),
    ];
    const liftedLuma = luminance(lifted[0], lifted[1], lifted[2]);
    const liftedCr = lifted[0] - liftedLuma;
    const liftedCb = lifted[2] - liftedLuma;
    let best = palette[0].hex;
    let bestDistance = Number.POSITIVE_INFINITY;
    for (const entry of palette) {
      const distance =
        (liftedLuma - entry.y) ** 2 +
        CHROMA_WEIGHT *
          ((liftedCr - entry.cr) ** 2 + (liftedCb - entry.cb) ** 2);
      if (distance < bestDistance) {
        bestDistance = distance;
        best = entry.hex;
      }
    }
    return best;
  };
  const BUCKET = 32;
  const buckets = new Map<string, TonedPrism[]>();
  for (const building of prisms.buildings) {
    if (!building.tone || building.ring.length < 3) {
      continue;
    }
    const ring = building.ring.map(
      ([x, z]) => [x / 10, z / 10] as [number, number],
    );
    const xs = ring.map(([x]) => x);
    const zs = ring.map(([, z]) => z);
    const toned: TonedPrism = {
      hex:
        building.id && KOLLHOFF_TOWER_PAYLOAD_IDS.has(building.id)
          ? KOLLHOFF_TOWER_PROFILE.minecraftClinkerTone
          : snap(building.tone),
      maxX: Math.max(...xs),
      maxZ: Math.max(...zs),
      minX: Math.min(...xs),
      minZ: Math.min(...zs),
      ring,
    };
    for (
      let bx = Math.floor(toned.minX / BUCKET);
      bx <= Math.floor(toned.maxX / BUCKET);
      bx += 1
    ) {
      for (
        let bz = Math.floor(toned.minZ / BUCKET);
        bz <= Math.floor(toned.maxZ / BUCKET);
        bz += 1
      ) {
        const key = `${bx},${bz}`;
        const list = buckets.get(key);
        if (list) {
          list.push(toned);
        } else {
          buckets.set(key, [toned]);
        }
      }
    }
  }
  const inside = (
    x: number,
    z: number,
    ring: Array<[number, number]>,
  ): boolean => {
    let odd = false;
    for (let i = 0, j = ring.length - 1; i < ring.length; j = i, i += 1) {
      const [xi, zi] = ring[i];
      const [xj, zj] = ring[j];
      if (zi > z !== zj > z && x < ((xj - xi) * (z - zi)) / (zj - zi) + xi) {
        odd = !odd;
      }
    }
    return odd;
  };
  return (x, z) => {
    const recognitionArea = voxelRecognitionAreaAt(x, z);
    if (recognitionArea) {
      return recognitionArea.tone;
    }
    const list = buckets.get(
      `${Math.floor(x / BUCKET)},${Math.floor(z / BUCKET)}`,
    );
    if (!list) {
      return null;
    }
    for (const toned of list) {
      if (
        x >= toned.minX &&
        x <= toned.maxX &&
        z >= toned.minZ &&
        z <= toned.maxZ &&
        inside(x, z, toned.ring)
      ) {
        return toned.hex;
      }
    }
    return null;
  };
}

/**
 * World-coordinate ground sampler: metres in, terrain-top metres out,
 * null outside the surveyed grid.
 */
export function worldGroundSampler(
  payload: VoxelPayload,
): (x: number, z: number) => number | null {
  const sample = groundTopSampler(payload);
  const cell = payload.cell_m;
  const { cols, min_x_idx, min_z_idx, rows } = payload.grid;
  return (x, z) => {
    const xOffset = x / cell - min_x_idx;
    const zOffset = z / cell - min_z_idx;
    if (xOffset < 0 || zOffset < 0 || xOffset >= cols || zOffset >= rows) {
      return null;
    }
    return sample(xOffset, zOffset);
  };
}

/**
 * Build the run-length ground slabs as one InstancedMesh. Shared between
 * the Minecraft voxel world and the drawn isometric city (which reuses
 * the same surveyed ground/water/road classes with its own palette).
 */
export function createGroundSlabs(
  payload: VoxelPayload,
  name: string,
  shadeMap: Record<string, readonly number[]>,
  options?: {
    bridgeDecks?: boolean;
    emissive?: number;
    skipClasses?: readonly string[];
    skipBridge?: boolean;
    skipBridgeAtWorld?: (x: number, z: number) => boolean;
    skipAtWorld?: (x: number, z: number) => boolean;
    skipWater?: boolean;
  },
): InstancedMesh {
  const cell = payload.cell_m;
  const { min_x_idx, min_z_idx } = payload.grid;
  const worldXAbs = (xIdx: number, span = 1): number =>
    (xIdx + span / 2) * cell;
  const worldZAbs = (zIdx: number): number => (zIdx + 0.5) * cell;
  const groundTopY = groundTopSampler(payload);
  const skippedClasses = new Set(options?.skipClasses ?? []);
  const visibleRuns: Array<{
    classId: number;
    run: number;
    xStart: number;
    zOffset: number;
  }> = [];
  let skippedByWorldPredicateCells = 0;
  let skippedBridgeCells = 0;
  payload.ground_rows.forEach((row, zOffset) => {
    for (const [xStart, run, classId] of row) {
      const className = payload.classes[classId] ?? "grass";
      if (
        skippedClasses.has(className) ||
        (options?.skipWater &&
          (className === "water" ||
            className === "basin" ||
            className === "pond")) ||
        (options?.skipBridge && className === "bridge")
      ) {
        continue;
      }
      const skipBridgeAtWorld =
        className === "bridge" ? options?.skipBridgeAtWorld : undefined;
      if (!options?.skipAtWorld && !skipBridgeAtWorld) {
        visibleRuns.push({ classId, run, xStart, zOffset });
        continue;
      }
      let visibleStart = -1;
      for (let step = 0; step < run; step += 1) {
        const xOffset = xStart + step;
        const worldX = worldXAbs(min_x_idx + xOffset);
        const worldZ = worldZAbs(min_z_idx + zOffset);
        const hiddenByWorld = options?.skipAtWorld?.(worldX, worldZ) ?? false;
        const hiddenBridge = skipBridgeAtWorld?.(worldX, worldZ) ?? false;
        const hidden = hiddenByWorld || hiddenBridge;
        if (!hidden && visibleStart < 0) {
          visibleStart = xOffset;
        }
        if (hidden) {
          if (hiddenByWorld) skippedByWorldPredicateCells += 1;
          if (hiddenBridge) skippedBridgeCells += 1;
          if (visibleStart >= 0) {
            visibleRuns.push({
              classId,
              run: xOffset - visibleStart,
              xStart: visibleStart,
              zOffset,
            });
            visibleStart = -1;
          }
        }
      }
      if (visibleStart >= 0) {
        visibleRuns.push({
          classId,
          run: xStart + run - visibleStart,
          xStart: visibleStart,
          zOffset,
        });
      }
    }
  });
  const ground = instancedBoxes(name, visibleRuns.length, options?.emissive);
  ground.mesh.userData.skippedByWorldPredicateCells =
    skippedByWorldPredicateCells;
  ground.mesh.userData.skippedBridgeCells = skippedBridgeCells;
  const center = new Vector3();
  const size = new Vector3();
  for (const { classId, run, xStart, zOffset } of visibleRuns) {
    const className = payload.classes[classId] ?? "grass";
    const shades = shadeMap[className] ?? shadeMap.grass ?? FALLBACK_SHADES;
    const topY =
      className === "water"
        ? (payload.water_top_y_m ?? WATER_TOP_Y)
        : groundTopY(xStart + run / 2, zOffset);
    // Real bridge decks (drawn city): a thin plate at bank level with
    // open air beneath, so the river visibly flows under the bridge
    // instead of the deck being ironed flat onto the water.
    const slabHeight =
      options?.bridgeDecks && className === "bridge" ? 1.1 : GROUND_SLAB_M;
    center.set(
      worldXAbs(min_x_idx + xStart, run),
      topY - slabHeight / 2,
      worldZAbs(min_z_idx + zOffset),
    );
    size.set(run * cell, slabHeight, cell);
    ground.write(center, size, shadeFor(shades, xStart, zOffset, run));
  }
  return ground.mesh;
}

type ExtrapolatedBlock = {
  color: number;
  position: [number, number, number];
  size: [number, number, number];
};

function addTiledBand(
  blocks: ExtrapolatedBlock[],
  band: readonly [number, number, number, number],
  toneOffset: number,
  centerY = 0.8,
  height = 2.6,
): void {
  const [centerX, centerZ, sizeX, sizeZ] = band;
  const tileM = 80;
  const minX = centerX - sizeX / 2;
  const minZ = centerZ - sizeZ / 2;
  const columns = Math.ceil(sizeX / tileM);
  const rows = Math.ceil(sizeZ / tileM);
  for (let row = 0; row < rows; row += 1) {
    const z0 = minZ + row * tileM;
    const depth = Math.min(tileM, minZ + sizeZ - z0);
    for (let column = 0; column < columns; column += 1) {
      const x0 = minX + column * tileM;
      const width = Math.min(tileM, minX + sizeX - x0);
      blocks.push({
        color: (column + row + toneOffset) % 2 === 0 ? 0x74b043 : 0x91bd59,
        position: [x0 + width / 2, centerY, z0 + depth / 2],
        size: [width, height, depth],
      });
    }
  }
}

function addBlockRoad(
  blocks: ExtrapolatedBlock[],
  from: readonly [number, number],
  to: readonly [number, number],
  widthM: number,
): void {
  const cellM = 4;
  const dx = to[0] - from[0];
  const dz = to[1] - from[1];
  const length = Math.hypot(dx, dz);
  const ux = dx / length;
  const uz = dz / length;
  const nx = -uz;
  const nz = ux;
  const alongCount = Math.ceil(length / cellM);
  const acrossCount = Math.ceil(widthM / cellM);
  for (let along = 0; along < alongCount; along += 1) {
    const distance = Math.min(length, along * cellM + cellM / 2);
    for (let across = 0; across < acrossCount; across += 1) {
      const lateral = (across + 0.5) * cellM - (acrossCount * cellM) / 2;
      blocks.push({
        color: (along + across) % 7 === 0 ? 0x40515c : 0x202923,
        position: [
          from[0] + ux * distance + nx * lateral,
          0.9,
          from[1] + uz * distance + nz * lateral,
        ],
        size: [cellM, 2.8, cellM],
      });
    }
  }
}

/**
 * Block counterpart of the versioned drawn surround. The official voxel
 * payload remains untouched; everything outside its grid is explicitly
 * marked as an extrapolated presentation layer.
 */
export function createMinecraftExtrapolatedWorld(): Group {
  const group = new Group();
  group.name = "Minecraft extrapolated radius surround";
  group.userData.extrapolated = true;
  group.userData.visibleRadiusM = VISIBLE_RADIUS_M;

  const groundBlocks: ExtrapolatedBlock[] = [];
  const envelope = extrapolatedEnvelopeBounds();
  addTiledBand(
    groundBlocks,
    [
      (envelope.minX + envelope.maxX) / 2,
      (envelope.minZ + envelope.maxZ) / 2,
      envelope.maxX - envelope.minX,
      envelope.maxZ - envelope.minZ,
    ],
    1,
    PRESENTATION_FLOOR_Y_M - 0.5,
    1,
  );
  extrapolatedMarginBands().forEach((band, index) => {
    addTiledBand(groundBlocks, band, index);
  });

  addBlockRoad(
    groundBlocks,
    [DATA_EAST_M, AXIS_FROM[1]],
    [DATA_EAST_M + EXTRAPOLATED_MARGIN_M, AXIS_FROM[1]],
    40,
  );

  const ground = instancedBoxes(
    "Voxel extrapolated ground and roads",
    groundBlocks.length,
  );
  for (const block of groundBlocks) {
    ground.write(
      new Vector3(...block.position),
      new Vector3(...block.size),
      new Color(block.color),
    );
  }
  group.add(ground.mesh);

  const columnParts: ExtrapolatedBlock[] = [
    {
      color: 0xc7c4b7,
      position: [AXIS_TO[0], 2.7, AXIS_TO[1]],
      size: [30, 1.2, 30],
    },
    {
      color: 0x994a35,
      position: [AXIS_TO[0], 6.25, AXIS_TO[1]],
      size: [26, 5.9, 26],
    },
    {
      color: SIEGESSAEULE_MOSAIC_TONES[0],
      position: [AXIS_TO[0], 11.6, AXIS_TO[1]],
      size: [10, 4.8, 10],
    },
    {
      color: 0xd4d4b7,
      position: [AXIS_TO[0], 14.35, AXIS_TO[1]],
      size: [19, 0.7, 19],
    },
    {
      color: 0xe8d1ae,
      position: [AXIS_TO[0], 36.1, AXIS_TO[1]],
      size: [9, 44, 9],
    },
    {
      color: 0xe6bd4c,
      position: [AXIS_TO[0], 59.6, AXIS_TO[1]],
      size: [12, 3, 12],
    },
    {
      color: 0xe6bd4c,
      position: [AXIS_TO[0], 64.1, AXIS_TO[1]],
      size: [3, 6, 3],
    },
    {
      color: 0xe6bd4c,
      position: [AXIS_TO[0], 65.2, AXIS_TO[1]],
      size: [9, 3, 1.5],
    },
    {
      color: 0xe6bd4c,
      position: [
        AXIS_TO[0],
        2.1 + SIEGESSAEULE_PROFILE.heightM - 1,
        AXIS_TO[1],
      ],
      size: [2, 2, 2],
    },
  ];
  const column = instancedBoxes(
    "Voxel extrapolated Siegessäule",
    columnParts.length,
  );
  for (const part of columnParts) {
    column.write(
      new Vector3(...part.position),
      new Vector3(...part.size),
      new Color(part.color),
    );
  }
  column.mesh.userData.animated = false;
  column.mesh.userData.groundTopY = 2.1;
  column.mesh.userData.renderedHeightM = SIEGESSAEULE_PROFILE.heightM;
  column.mesh.userData.renderedTopY = 2.1 + SIEGESSAEULE_PROFILE.heightM;
  group.add(column.mesh);

  // The four historic bronze reliefs belong to the lower red-granite base,
  // not to the mosaic storey above it.  One shallow block per face preserves
  // that two-register reading without importing smooth geometry or textures.
  const bronzeReliefParts: ExtrapolatedBlock[] = [
    {
      color: SIEGESSAEULE_BRONZE_TONES.field,
      position: [AXIS_TO[0], 6.25, AXIS_TO[1] - 13.16],
      size: [11.8, 2.1, 0.48],
    },
    {
      color: SIEGESSAEULE_BRONZE_TONES.highlight,
      position: [AXIS_TO[0], 6.25, AXIS_TO[1] + 13.16],
      size: [11.8, 2.1, 0.48],
    },
    {
      color: SIEGESSAEULE_BRONZE_TONES.field,
      position: [AXIS_TO[0] - 13.16, 6.25, AXIS_TO[1]],
      size: [0.48, 2.1, 11.8],
    },
    {
      color: SIEGESSAEULE_BRONZE_TONES.highlight,
      position: [AXIS_TO[0] + 13.16, 6.25, AXIS_TO[1]],
      size: [0.48, 2.1, 11.8],
    },
  ];
  const bronzeReliefs = instancedBoxes(
    "Voxel Siegessäule lower bronze relief panels",
    bronzeReliefParts.length,
  );
  for (const part of bronzeReliefParts) {
    bronzeReliefs.write(
      new Vector3(...part.position),
      new Vector3(...part.size),
      new Color(part.color),
    );
  }
  bronzeReliefs.mesh.userData.animated = false;
  bronzeReliefs.mesh.userData.architecturalLevel =
    SIEGESSAEULE_PROFILE.reliefs.architecturalLevel;
  bronzeReliefs.mesh.userData.blockNative = true;
  bronzeReliefs.mesh.userData.textureFree = true;
  group.add(bronzeReliefs.mesh);

  // One merged, block-native colour register on the four outward faces of
  // the inner hall core.  It remains visibly behind a separate ring of 16
  // marble blocks, so Minecraft does not flatten the upper mosaic and lower
  // bronze-bearing base into the same cube.
  const mosaicBandParts: ExtrapolatedBlock[] = [];
  const bandOffsets = [-3, -1, 1, 3] as const;
  for (let face = 0; face < 4; face += 1) {
    for (let index = 0; index < bandOffsets.length; index += 1) {
      const along = bandOffsets[index];
      const tone =
        SIEGESSAEULE_MOSAIC_TONES[
          1 +
            ((face * bandOffsets.length + index) %
              (SIEGESSAEULE_MOSAIC_TONES.length - 1))
        ];
      const xFace = face >= 2;
      const sign = face % 2 === 0 ? -1 : 1;
      mosaicBandParts.push({
        color: tone,
        position: [
          AXIS_TO[0] + (xFace ? sign * 5.18 : along),
          11.75 + ((face + index) % 2) * 0.32,
          AXIS_TO[1] + (xFace ? along : sign * 5.18),
        ],
        size: xFace ? [0.42, 1.35, 1.7] : [1.7, 1.35, 0.42],
      });
    }
  }
  const mosaicBand = instancedBoxes(
    "Voxel Siegessäule glass mosaic colour band",
    mosaicBandParts.length,
  );
  for (const part of mosaicBandParts) {
    mosaicBand.write(
      new Vector3(...part.position),
      new Vector3(...part.size),
      new Color(part.color),
    );
  }
  mosaicBand.mesh.userData.animated = false;
  mosaicBand.mesh.userData.architecturalLevel =
    SIEGESSAEULE_PROFILE.mosaic.architecturalLevel;
  mosaicBand.mesh.userData.blockNative = true;
  mosaicBand.mesh.userData.textureFree = true;
  group.add(mosaicBand.mesh);

  const colonnadeParts: ExtrapolatedBlock[] = [];
  const hallRadius = SIEGESSAEULE_PROFILE.colonnade.diameterM / 2;
  for (
    let index = 0;
    index < SIEGESSAEULE_PROFILE.colonnade.columnCount;
    index += 1
  ) {
    const angle =
      (index / SIEGESSAEULE_PROFILE.colonnade.columnCount) * Math.PI * 2;
    colonnadeParts.push({
      color: index % 2 === 0 ? 0xe7e0c9 : 0xd4d4b7,
      position: [
        AXIS_TO[0] + Math.cos(angle) * hallRadius,
        11.7,
        AXIS_TO[1] + Math.sin(angle) * hallRadius,
      ],
      size: [0.9, 4.1, 0.9],
    });
  }
  const colonnade = instancedBoxes(
    "Voxel Siegessäule upper colonnade",
    colonnadeParts.length,
  );
  for (const part of colonnadeParts) {
    colonnade.write(
      new Vector3(...part.position),
      new Vector3(...part.size),
      new Color(part.color),
    );
  }
  colonnade.mesh.userData.animated = false;
  colonnade.mesh.userData.blockNative = true;
  colonnade.mesh.userData.textureFree = true;
  group.add(colonnade.mesh);

  for (const child of group.children) {
    if (child instanceof InstancedMesh) {
      child.instanceMatrix.needsUpdate = true;
      if (child.instanceColor) {
        child.instanceColor.needsUpdate = true;
      }
      child.frustumCulled = false;
    }
  }
  return group;
}

/**
 * One stepped, block-native front for the Hamburger Bahnhof. The surveyed
 * voxel columns remain the building mass; this single instanced overlay gives
 * that mass its actual flat head-building hierarchy without importing the
 * smooth Day/Night drawing into Minecraft mode.
 */
export function createMinecraftHamburgerBahnhofRecognition(): InstancedMesh {
  const facade = HAMBURGER_BAHNHOF_VOXEL_FACADE;
  const blocks: ExtrapolatedBlock[] = [];
  const at = (u: number, outward: number): [number, number] => [
    facade.center[0] + facade.axis[0] * u + facade.normal[0] * outward,
    facade.center[1] + facade.axis[1] * u + facade.normal[1] * outward,
  ];
  const push = (
    color: number,
    u: number,
    y: number,
    outward: number,
    size: readonly [number, number, number],
  ): void => {
    const [x, z] = at(u, outward);
    blocks.push({ color, position: [x, y, z], size: [...size] });
  };

  // A two-metre stepped facade follows the real 30 degree line. The towers
  // rise to the measured 26 m level; the main hall and wings remain lower.
  for (let u = -30; u <= 30; u += 2) {
    const tower = Math.abs(Math.abs(u) - 12) <= 2;
    const centre = Math.abs(u) <= 10;
    const top = tower ? 26 : centre ? 20 : 15;
    for (let y = facade.groundY + 1; y < facade.groundY + top; y += 2) {
      push(0xe8d1ae, u, y, -0.25, [1.82, 1.82, 1.3]);
    }
  }

  // Cornice courses remain block rows rather than smooth mouldings.
  for (let u = -30; u <= 30; u += 2) {
    const y = facade.groundY + (Math.abs(u) <= 11 ? 20 : 15);
    push(0xf3efd0, u, y, 0.48, [1.9, 0.72, 1.45]);
  }

  // Six green upper arcades, two large dark hall arches and two timber doors.
  for (const u of [-7.5, -4.5, -1.5, 1.5, 4.5, 7.5]) {
    for (const y of [14.2, 16.2, 18.2]) {
      push(0x74b043, u, facade.groundY + y, 0.86, [1.35, 1.65, 0.68]);
    }
  }
  for (const u of [-4.4, 4.4]) {
    for (const du of [-2, 0, 2]) {
      for (const y of [7.1, 9.1, 11.1]) {
        push(0x40515c, u + du, facade.groundY + y, 0.9, [1.55, 1.6, 0.7]);
      }
    }
    push(0x994a35, u, facade.groundY + 2.2, 0.96, [2.1, 4.1, 0.72]);
  }

  // Three belfry slots in each measured tower and a pale clock/rosette block.
  for (const towerU of [-11.43, 11.43]) {
    for (const du of [-1.35, 0, 1.35]) {
      push(0x40515c, towerU + du, facade.groundY + 23, 0.9, [0.82, 2.8, 0.7]);
    }
    push(0xd6dfe0, towerU, facade.groundY + 18.8, 0.94, [1.7, 1.7, 0.72]);
  }

  const writer = instancedBoxes(
    "Voxel Hamburger Bahnhof recognition facade",
    blocks.length,
  );
  for (const block of blocks) {
    writer.write(
      new Vector3(...block.position),
      new Vector3(...block.size),
      new Color(block.color),
    );
  }
  writer.mesh.instanceMatrix.needsUpdate = true;
  if (writer.mesh.instanceColor) writer.mesh.instanceColor.needsUpdate = true;
  writer.mesh.frustumCulled = false;
  writer.mesh.userData.architecturalProfile = {
    lowerHallArches: 2,
    roofForm: "flat-cornice",
    towerHeightM: 26,
    upperArcades: 6,
  };
  return writer.mesh;
}

/**
 * One deliberately block-native reading of the Sozialgericht's public front.
 *
 * The complete LoD2 prism remains the building and collision authority. This
 * thin overlay replaces only the generic square-office fenestration at the
 * exact LoD2 facade edge with its 4 + 3 + 4 rhythm, broad central risalit,
 * Portal 52, stepped pediment and three compact roof-sculpture silhouettes.
 */
export function createMinecraftSocialCourtRecognition(
  detailProfile: MinecraftVoxelDetailProfile = "full",
): InstancedMesh {
  const profile = SOCIAL_COURT_PROFILE;
  const blocks: ExtrapolatedBlock[] = [];
  const push = (
    color: number,
    localX: number,
    y: number,
    outward: number,
    size: readonly [number, number, number],
  ): void => {
    const [x, z] = socialCourtFacadeWorldAt(localX, -outward);
    blocks.push({ color, position: [x, y, z], size: [...size] });
  };

  const groundY = profile.groundY;
  const pitch = profile.facade.bayPitchM;
  const bayCentres = profile.facade.bayCentresM;
  const risalitCenterX = profile.facade.risalitCenterLocalXM;
  const portalCenterX = profile.portal.centerLocalXM;
  const sandstone = 0xe8d1ae;
  const sandstoneLight = 0xf3efd0;
  const sandstoneShadow = 0xd4b98d;
  const granite = 0x8e9a9e;
  const glass = VOXEL_WINDOW_TEAL;
  const frame = 0x40515c;
  const wood = 0x715b4a;
  const amber = 0xe6bd4c;
  const metal = 0x34443a;

  // Three continuous source-height courses and a granite plinth keep the
  // facade visibly made of blocks even on mobile, where generic city columns
  // would otherwise be one smooth 20 m cuboid.
  const bandStep = detailProfile === "full" ? 2 : 4;
  for (
    let localX = -profile.facade.facadeLengthM / 2 + bandStep / 2;
    localX < profile.facade.facadeLengthM / 2;
    localX += bandStep
  ) {
    const width = Math.min(
      bandStep - 0.12,
      profile.facade.facadeLengthM / 2 - localX + bandStep / 2,
    );
    push(granite, localX, groundY + 0.5, 0.68, [width, 0.9, 1.05]);
    for (const [y, height, depth, color] of [
      [groundY + 7.42, 0.68, 1.18, sandstoneLight],
      [groundY + 12.34, 0.52, 1.05, sandstoneShadow],
      [groundY + 16.5, 0.82, 1.35, sandstoneLight],
    ] as const) {
      push(color, localX, y, 0.72, [width, height, depth]);
    }
  }

  // Ten lower arches, eight tall wing windows and eight paired upper
  // openings. Each opening uses a tiny number of coarse panes on purpose.
  for (const [index, localX] of bayCentres.entries()) {
    const central = index >= 4 && index <= 6;
    const authoredLocalX = central ? localX + risalitCenterX : localX;
    if (index !== 5) {
      push(frame, authoredLocalX, groundY + 4.7, 0.97, [2.7, 4.2, 0.52]);
      push(glass, authoredLocalX, groundY + 4.45, 1.06, [2.1, 3.45, 0.38]);
      push(sandstoneLight, authoredLocalX, groundY + 2.25, 1.02, [
        3.3, 0.42, 0.74,
      ]);
    }
    if (!central) {
      push(frame, localX, groundY + 9.92, 0.96, [2.65, 4.0, 0.5]);
      push(glass, localX, groundY + 9.75, 1.05, [2.05, 3.36, 0.36]);
      push(sandstoneLight, localX, groundY + 12.12, 1.01, [3.65, 0.48, 0.78]);
      for (const side of [-1, 1]) {
        push(
          glass,
          localX + side * 0.72,
          groundY + 14.03,
          1.03,
          [1.05, 2.25, 0.36],
        );
      }
    }
  }

  // Broad three-axis risalit and coupled tall windows with three oculi.
  for (
    let localX = risalitCenterX - profile.facade.risalitWidthM / 2 + 1;
    localX < risalitCenterX + profile.facade.risalitWidthM / 2;
    localX += 2
  ) {
    push(sandstone, localX, groundY + 8.4, 0.76, [1.88, 15.9, 1.05]);
  }
  for (const localX of [
    risalitCenterX - pitch,
    risalitCenterX,
    risalitCenterX + pitch,
  ]) {
    for (const side of [-1, 1]) {
      push(
        glass,
        localX + side * 1.25,
        groundY + 10.02,
        1.42,
        [1.55, 4.7, 0.42],
      );
    }
    // Square-pixel ring around a dark centre: unmistakably an oculus while
    // remaining faithful to Minecraft's orthogonal vocabulary.
    push(sandstoneLight, localX, groundY + 14.05, 1.36, [3.3, 3.3, 0.5]);
    push(glass, localX, groundY + 14.05, 1.47, [2.15, 2.15, 0.36]);
    push(frame, localX, groundY + 14.05, 1.58, [2.2, 0.22, 0.24]);
    push(frame, localX, groundY + 14.05, 1.58, [0.22, 2.2, 0.24]);
  }
  for (const localX of [
    risalitCenterX - 1.55 * pitch,
    risalitCenterX - 0.5 * pitch,
    risalitCenterX + 0.5 * pitch,
    risalitCenterX + 1.55 * pitch,
  ]) {
    push(sandstoneLight, localX, groundY + 11.05, 1.48, [0.74, 7.35, 0.72]);
  }

  // Portal 52, six block steps and two handrail posts. Amber blocks preserve
  // the numbered transom without importing a font or a photograph.
  push(wood, portalCenterX, groundY + 3.35, 1.86, [4.3, 4.45, 0.62]);
  push(frame, portalCenterX, groundY + 3.35, 1.98, [0.22, 4.2, 0.3]);
  push(amber, portalCenterX, groundY + 6.0, 1.9, [3.45, 1.05, 0.54]);
  const addressGlyphs = {
    "2": ["111", "001", "111", "100", "111"],
    "5": ["111", "100", "111", "001", "111"],
  } as const;
  let addressPixelCount = 0;
  for (const [digitX, digit] of [
    [-0.42, "5"],
    [0.42, "2"],
  ] as const) {
    for (const [row, pixels] of addressGlyphs[digit].entries()) {
      for (let column = 0; column < pixels.length; column += 1) {
        if (pixels[column] !== "1") continue;
        push(
          metal,
          portalCenterX + digitX + (column - 1) * 0.13,
          groundY + 6.25 - row * 0.13,
          2.22,
          [0.1, 0.1, 0.18],
        );
        addressPixelCount += 1;
      }
    }
  }
  for (const side of [-1, 1]) {
    push(sandstoneLight, portalCenterX + side * 3.15, groundY + 4.05, 1.45, [
      1.08, 6.25, 1.05,
    ]);
    push(metal, portalCenterX + side * 2.45, groundY + 1.15, 2.85, [
      0.18, 1.6, 0.18,
    ]);
  }
  for (let step = 0; step < profile.portal.stepCount; step += 1) {
    const t = step / (profile.portal.stepCount - 1);
    push(
      granite,
      portalCenterX,
      groundY + 0.12 + step * 0.2,
      3.15 - step * 0.4,
      [7.5 - t * 1.7, 0.22, 0.72],
    );
  }

  // The photo-backed front gable is a stepped triangle, never the former
  // detached dark roof block. Three separated graphite sculpture clusters
  // and the bare mast finish the silhouette.
  for (let row = 0; row < 4; row += 1) {
    push(
      row === 3 ? sandstoneLight : sandstone,
      risalitCenterX,
      groundY + 17.35 + row * 0.72,
      0.92,
      [profile.facade.risalitWidthM - row * 4.0, 0.78, 1.25],
    );
  }
  for (const side of [-1, 1]) {
    const shoulderX =
      risalitCenterX + side * profile.facade.risalitWidthM * 0.414;
    push(metal, shoulderX, groundY + 18.38, 0.88, [3.0, 1.1, 1.45]);
    push(
      metal,
      shoulderX - side * 0.62,
      groundY + 19.02,
      0.9,
      [0.9, 1.15, 1.0],
    );
  }
  push(metal, risalitCenterX, groundY + 20.22, 0.88, [6.2, 0.62, 1.45]);
  push(metal, risalitCenterX, groundY + 21.45, 0.9, [1.1, 2.4, 1.0]);
  push(metal, risalitCenterX - 1.65, groundY + 20.92, 0.9, [
    1.25, 1.35, 1.0,
  ]);
  push(metal, risalitCenterX + 1.65, groundY + 20.92, 0.9, [
    1.25, 1.35, 1.0,
  ]);
  push(metal, risalitCenterX, groundY + 25.0, 0.35, [0.18, 6.3, 0.18]);

  const writer = instancedBoxes(
    "Voxel Sozialgericht Berlin 11-axis recognition facade",
    blocks.length,
  );
  for (const block of blocks) {
    writer.write(
      new Vector3(...block.position),
      new Vector3(...block.size),
      new Color(block.color),
      profile.facade.rotationY,
    );
  }
  writer.mesh.instanceMatrix.needsUpdate = true;
  if (writer.mesh.instanceColor) writer.mesh.instanceColor.needsUpdate = true;
  writer.mesh.frustumCulled = false;
  writer.mesh.userData = {
    addressPixelCount,
    architecturalProfile: profile,
    blockCount: blocks.length,
    detailProfile,
    keepInMinecraft: true,
    sourceBound: true,
    textureFree: true,
  };
  return writer.mesh;
}

/**
 * Block-native planning envelope for berlin modern.
 *
 * The completed museum is absent from the surveyed LoD2 payload while it is
 * under construction. This explicit approximation keeps Minecraft consistent
 * with the Day/Night model without importing its smooth roof geometry.
 */
export function createMinecraftBerlinModernRecognition(): InstancedMesh {
  const profile = BERLIN_MODERN_PROFILE;
  const columns = 18;
  const rows = 30;
  const cellWidth = profile.footprintWidthM / columns;
  const cellDepth = profile.footprintLengthM / rows;
  const glassColumns = 12;
  const glassRows = 3;
  const writer = instancedBoxes(
    "Voxel berlin modern planning envelope",
    columns * rows * 2 + glassColumns * glassRows,
  );
  const center = new Vector3();
  const size = new Vector3();
  const [originX, originZ] = profile.centerWorldM;
  const cosine = Math.cos(profile.rotationY);
  const sine = Math.sin(profile.rotationY);
  const at = (localX: number, localZ: number): [number, number] => [
    originX + localX * cosine + localZ * sine,
    originZ - localX * sine + localZ * cosine,
  ];

  for (let row = 0; row < rows; row += 1) {
    const localZ = -profile.footprintLengthM / 2 + (row + 0.5) * cellDepth;
    for (let column = 0; column < columns; column += 1) {
      const localX = -profile.footprintWidthM / 2 + (column + 0.5) * cellWidth;
      const roofTop =
        profile.groundY +
        profile.bodyHeightM +
        profile.roofRiseM *
          (1 - Math.abs(localX) / (profile.footprintWidthM / 2));
      const roofCapHeight = 1.15;
      const bodyHeight = roofTop - profile.groundY - roofCapHeight;
      const [x, z] = at(localX, localZ);
      center.set(x, profile.groundY + bodyHeight / 2, z);
      size.set(cellWidth - 0.08, bodyHeight, cellDepth - 0.08);
      writer.write(
        center,
        size,
        new Color((row + column) % 5 === 0 ? 0xf3efd0 : 0xe8d1ae),
        profile.rotationY,
      );
      center.set(x, roofTop - roofCapHeight / 2, z);
      size.set(cellWidth - 0.08, roofCapHeight, cellDepth - 0.08);
      writer.write(
        center,
        size,
        new Color((row + column) % 4 === 0 ? 0x40515c : 0x34443a),
        profile.rotationY,
      );
    }
  }

  // Three block rows reproduce the broad north entrance without generic
  // black square windows.
  for (let row = 0; row < glassRows; row += 1) {
    for (let column = 0; column < glassColumns; column += 1) {
      const localX = -24 + (column + 0.5) * 4;
      const [x, z] = at(localX, -profile.footprintLengthM / 2 - 0.36);
      center.set(x, profile.groundY + 1.8 + row * 3, z);
      size.set(3.55, 2.55, 0.62);
      writer.write(
        center,
        size,
        new Color((column + row) % 3 === 0 ? 0xa4dfe2 : 0x72c5d2),
        profile.rotationY,
      );
    }
  }

  writer.mesh.instanceMatrix.needsUpdate = true;
  if (writer.mesh.instanceColor) writer.mesh.instanceColor.needsUpdate = true;
  writer.mesh.frustumCulled = false;
  writer.mesh.userData.architecturalProfile = profile;
  return writer.mesh;
}

/** Block-native KPMG/EINZ facade and current temporary Europaplatz Nord. */
export function createMinecraftEinzEuropaplatzRecognition(): InstancedMesh {
  const profile = EUROPACITY_PROFILE.einz;
  const plaza = EUROPACITY_PROFILE.europaplatzNorth;
  const campus = EUROPACITY_PROFILE.lehrterCampus;
  const writer = instancedBoxes("Voxel KPMG and Europaplatz Nord", 1_300);
  const center = new Vector3();
  const size = new Vector3();
  const color = new Color();
  const writeAt = (
    origin: readonly [number, number],
    rotationY: number,
    localX: number,
    centerY: number,
    localZ: number,
    width: number,
    height: number,
    depth: number,
    tone: number,
  ): void => {
    const cosine = Math.cos(rotationY);
    const sine = Math.sin(rotationY);
    center.set(
      origin[0] + localX * cosine + localZ * sine,
      centerY,
      origin[1] - localX * sine + localZ * cosine,
    );
    size.set(width, height, depth);
    writer.write(center, size, color.setHex(tone), rotationY);
  };
  const tower = (
    localX: number,
    centerY: number,
    localZ: number,
    width: number,
    height: number,
    depth: number,
    tone: number,
  ): void =>
    writeAt(
      profile.centerWorldM,
      profile.rotationY,
      localX,
      centerY,
      localZ,
      width,
      height,
      depth,
      tone,
    );
  const floorPitch = profile.measuredHeightM / profile.floorCount;

  // Calm blue-grey curtain-wall faces. The payload supplies the surveyed
  // tower mass; this overlay replaces its generic square-window treatment.
  for (const side of [-1, 1]) {
    tower(
      0,
      profile.groundY + profile.measuredHeightM / 2,
      side * (profile.footprintDepthM / 2 + 0.18),
      profile.footprintLengthM,
      profile.measuredHeightM,
      0.45,
      side > 0 ? 0x72c5d2 : 0x5f8790,
    );
    tower(
      side * (profile.footprintLengthM / 2 + 0.18),
      profile.groundY + profile.measuredHeightM / 2,
      0,
      0.45,
      profile.measuredHeightM,
      profile.footprintDepthM,
      side > 0 ? 0xa4dfe2 : 0x72c5d2,
    );
    for (let floor = 0; floor <= profile.floorCount; floor += 1) {
      const y = profile.groundY + floorPitch * floor;
      tower(
        0,
        y,
        side * (profile.footprintDepthM / 2 + 0.48),
        profile.footprintLengthM + 0.5,
        0.36,
        0.52,
        0xd4d4b7,
      );
      tower(
        side * (profile.footprintLengthM / 2 + 0.48),
        y,
        0,
        0.52,
        0.36,
        profile.footprintDepthM + 0.5,
        0xd4d4b7,
      );
    }
  }
  for (
    let localX = -profile.footprintLengthM / 2;
    localX <= profile.footprintLengthM / 2;
    localX += profile.facadeGridM * 2
  ) {
    for (const side of [-1, 1]) {
      tower(
        localX,
        profile.groundY + profile.measuredHeightM / 2,
        side * (profile.footprintDepthM / 2 + 0.5),
        0.32,
        profile.measuredHeightM,
        0.42,
        0xf3efd0,
      );
    }
  }
  for (
    let localZ = -profile.footprintDepthM / 2;
    localZ <= profile.footprintDepthM / 2;
    localZ += profile.facadeGridM * 2
  ) {
    for (const side of [-1, 1]) {
      tower(
        side * (profile.footprintLengthM / 2 + 0.5),
        profile.groundY + profile.measuredHeightM / 2,
        localZ,
        0.42,
        profile.measuredHeightM,
        0.32,
        0xf3efd0,
      );
    }
  }
  tower(
    0,
    profile.groundY + profile.measuredHeightM - 0.55,
    0,
    profile.footprintLengthM + 0.8,
    1.1,
    profile.footprintDepthM + 0.8,
    0xb8b4a8,
  );

  // Small upper-corner lettering cue instead of an oversized billboard.
  tower(
    -13.4,
    profile.groundY + profile.measuredHeightM - 4.1,
    -(profile.footprintDepthM / 2 + 0.76),
    6,
    1.6,
    0.34,
    0xf3efd0,
  );
  for (const localX of [-15.1, -13.95, -12.8, -11.65]) {
    tower(
      localX,
      profile.groundY + profile.measuredHeightM - 4.1,
      -(profile.footprintDepthM / 2 + 0.96),
      0.42,
      0.78,
      0.22,
      0x40515c,
    );
  }

  const podium = profile.podium;
  const podiumBox = (
    localX: number,
    centerY: number,
    localZ: number,
    width: number,
    height: number,
    depth: number,
    tone: number,
  ): void =>
    writeAt(
      podium.centerWorldM,
      profile.rotationY,
      localX,
      centerY,
      localZ,
      width,
      height,
      depth,
      tone,
    );
  podiumBox(
    0,
    profile.groundY + podium.measuredHeightM / 2,
    0,
    podium.footprintLengthM,
    podium.measuredHeightM,
    podium.footprintDepthM,
    0x72c5d2,
  );
  for (let floor = 0; floor <= podium.floorCount; floor += 1) {
    const y =
      profile.groundY + (podium.measuredHeightM * floor) / podium.floorCount;
    for (const side of [-1, 1]) {
      podiumBox(
        0,
        y,
        side * (podium.footprintDepthM / 2 + 0.35),
        podium.footprintLengthM,
        0.42,
        0.42,
        0xd4d4b7,
      );
      podiumBox(
        side * (podium.footprintLengthM / 2 + 0.35),
        y,
        0,
        0.42,
        0.42,
        podium.footprintDepthM,
        0xd4d4b7,
      );
    }
  }

  const plazaBox = (
    localX: number,
    centerY: number,
    localZ: number,
    width: number,
    height: number,
    depth: number,
    tone: number,
  ): void =>
    writeAt(
      plaza.centerWorldM,
      plaza.rotationY,
      localX,
      centerY,
      localZ,
      width,
      height,
      depth,
      tone,
    );
  plazaBox(
    0,
    plaza.groundY + 0.32,
    0,
    plaza.footprintLengthM,
    0.64,
    plaza.footprintDepthM,
    0xd4d4b7,
  );
  for (const [localX, localZ, width, depth] of [
    [-34, 8, 28, 21],
    [31, -7, 31, 18],
  ] as const) {
    plazaBox(
      localX,
      plaza.groundY + 0.68,
      localZ,
      width,
      0.72,
      depth,
      0x715b4a,
    );
    let barrierIndex = 0;
    for (let offset = -width / 2 + 1.5; offset < width / 2; offset += 3) {
      for (const edgeZ of [-depth / 2 - 0.5, depth / 2 + 0.5]) {
        plazaBox(
          localX + offset,
          plaza.groundY + 1.35,
          localZ + edgeZ,
          2.6,
          1.1,
          0.55,
          barrierIndex++ % 2 === 0 ? 0xc84038 : 0xf3efd0,
        );
      }
    }
  }
  let treeIndex = 0;
  for (const localZ of [-22, 23]) {
    for (let localX = -42; localX <= 42; localX += 14) {
      const stagger = treeIndex++ % 2 === 0 ? -0.7 : 0.7;
      plazaBox(
        localX,
        plaza.groundY + 2,
        localZ + stagger,
        0.6,
        3.4,
        0.6,
        0x704a2d,
      );
      plazaBox(
        localX,
        plaza.groundY + 4.2,
        localZ + stagger,
        2.8,
        2.4,
        2.8,
        treeIndex % 3 === 0 ? 0x74b043 : 0x5d9634,
      );
    }
  }

  // Block-native present-day Lehrter Campus: low concrete frame, scaffold,
  // hoarding and crane. Do not voxelise the published 35.5 m finished mass
  // while the owner reference still records a ground-floor construction site.
  const campusBox = (
    x: number,
    centerY: number,
    z: number,
    width: number,
    height: number,
    depth: number,
    tone: number,
    rotationY = 0,
  ): void => {
    center.set(x, centerY, z);
    size.set(width, height, depth);
    writer.write(center, size, color.setHex(tone), rotationY);
  };
  campusBox(-260, campus.groundY + 0.45, -714, 28, 0.9, 61, 0xa9aaa6);
  campusBox(
    -260,
    campus.groundY + campus.currentSlabTopM - 0.35,
    -714,
    24,
    0.7,
    54,
    0xd4d4ce,
  );
  for (const x of [-270, -261, -252]) {
    for (const z of [-738, -725, -712, -699, -688]) {
      campusBox(
        x,
        campus.groundY + campus.currentSlabTopM / 2,
        z,
        0.9,
        campus.currentSlabTopM,
        0.9,
        0xa9aaa6,
      );
    }
  }
  for (let z = -741; z <= -688; z += 4) {
    for (const x of [-274.5, -246.5]) {
      campusBox(
        x,
        campus.groundY + campus.currentScaffoldTopM / 2,
        z,
        0.35,
        campus.currentScaffoldTopM,
        0.35,
        0x59615f,
      );
    }
  }
  for (const y of [1.4, 4, 6.6, 9.2]) {
    campusBox(-246.5, campus.groundY + y, -714, 0.35, 0.35, 56, 0x59615f);
    campusBox(-274.5, campus.groundY + y, -714, 0.35, 0.35, 56, 0x59615f);
  }
  campusBox(-260.5, campus.groundY + 1.5, -745, 26, 3, 0.65, 0x252d2d);
  campusBox(-246, campus.groundY + 1.5, -714, 0.65, 3, 58, 0x252d2d);
  campusBox(
    campus.craneWorldM[0],
    campus.groundY + campus.craneMastHeightM / 2,
    campus.craneWorldM[1],
    1.8,
    campus.craneMastHeightM,
    1.8,
    0x59615f,
  );
  campusBox(
    campus.craneWorldM[0] + 10.8,
    campus.groundY + campus.craneMastHeightM,
    campus.craneWorldM[1] + 4.1,
    47,
    1.15,
    1.15,
    0x59615f,
    -0.36,
  );

  writer.mesh.instanceMatrix.needsUpdate = true;
  if (writer.mesh.instanceColor) writer.mesh.instanceColor.needsUpdate = true;
  writer.mesh.frustumCulled = false;
  writer.mesh.userData.architecturalProfile = {
    campus,
    plaza,
    tower: profile,
  };
  writer.mesh.userData.sourceRole =
    "LoD2-tower-current-2026-forecourt-and-Lehrter-Campus-construction";
  return writer.mesh;
}

/**
 * Block-native Upbeat volume from the same current OSM outline and published
 * 5/11/19-storey height register as the drawn model. The current LoD2 payload
 * predates this building, so without this fill the Minecraft focus lands on an
 * empty plot.
 */
export function createMinecraftUpbeatRecognition(): InstancedMesh {
  const profile = EUROPACITY_PROFILE.upbeat;
  const ring = profile.footprintWorldM;
  const minimumX = Math.min(...ring.map(([x]) => x));
  const maximumX = Math.max(...ring.map(([x]) => x));
  const minimumZ = Math.min(...ring.map(([, z]) => z));
  const maximumZ = Math.max(...ring.map(([, z]) => z));
  const cellM = 3;
  const contains = (x: number, z: number): boolean => {
    let inside = false;
    for (let index = 0, previous = ring.length - 1; index < ring.length;) {
      const [x1, z1] = ring[index];
      const [x2, z2] = ring[previous];
      const crosses =
        z1 > z !== z2 > z && x < ((x2 - x1) * (z - z1)) / (z2 - z1) + x1;
      if (crosses) inside = !inside;
      previous = index;
      index += 1;
    }
    return inside;
  };
  const baseTop = profile.groundY + profile.tierTopHeightsM[0];
  const middleTop = profile.groundY + profile.tierTopHeightsM[1];
  const towerTop = profile.groundY + profile.tierTopHeightsM[2];
  const blocks: ExtrapolatedBlock[] = [];
  for (let x = minimumX + cellM / 2; x < maximumX; x += cellM) {
    for (let z = minimumZ + cellM / 2; z < maximumZ; z += cellM) {
      if (!contains(x, z)) continue;
      const top =
        x >= profile.towerTierEastClipWorldX
          ? towerTop
          : x >= profile.midTierEastClipWorldX
            ? middleTop
            : baseTop;
      const bodyHeight = top - profile.groundY - 1;
      const cellIndex =
        Math.round((x - minimumX) / cellM) + Math.round((z - minimumZ) / cellM);
      blocks.push({
        color: cellIndex % 5 === 0 ? 0x72c5d2 : 0xa4dfe2,
        position: [x, profile.groundY + bodyHeight / 2, z],
        size: [cellM - 0.12, bodyHeight, cellM - 0.12],
      });
      blocks.push({
        color: cellIndex % 4 === 0 ? 0xd4d4b7 : 0xf3efd0,
        position: [x, top - 0.5, z],
        size: [cellM - 0.08, 1, cellM - 0.08],
      });
    }
  }
  const writer = instancedBoxes("Voxel Upbeat Europacity", blocks.length);
  for (const block of blocks) {
    writer.write(
      new Vector3(...block.position),
      new Vector3(...block.size),
      new Color(block.color),
    );
  }
  writer.mesh.instanceMatrix.needsUpdate = true;
  if (writer.mesh.instanceColor) writer.mesh.instanceColor.needsUpdate = true;
  writer.mesh.frustumCulled = false;
  writer.mesh.userData.architecturalProfile = profile;
  writer.mesh.userData.sourceRole = "OSM-footprint-published-height";
  return writer.mesh;
}

/** Block-native counterpart of the temporary 2026 FUNBOX event park. */
export function createMinecraftFunboxRecognition(): InstancedMesh {
  const profile = NORTHERN_CITY_PROFILE.funbox;
  const colors = [
    0xe84d42, 0xf28a38, 0x367fc8, 0x45a85f, 0x8d62bd, 0xf5c83f,
  ] as const;
  const blocks: ExtrapolatedBlock[] = [];
  const cosine = Math.cos(profile.rotationY);
  const sine = Math.sin(profile.rotationY);
  const at = (localX: number, localZ: number): [number, number] => [
    profile.centerWorldM[0] + localX * cosine + localZ * sine,
    profile.centerWorldM[1] - localX * sine + localZ * cosine,
  ];
  const push = (
    color: number,
    localX: number,
    centerY: number,
    localZ: number,
    size: readonly [number, number, number],
  ): void => {
    const [x, z] = at(localX, localZ);
    blocks.push({ color, position: [x, centerY, z], size: [...size] });
  };

  const zoneDepth = profile.footprintLengthM / profile.sourceZoneCount;
  for (let zone = 0; zone < profile.sourceZoneCount; zone += 1) {
    push(
      colors[zone % colors.length],
      0,
      profile.groundY + 0.5,
      -profile.footprintLengthM / 2 + zoneDepth * (zone + 0.5),
      [profile.footprintWidthM - 2, 1, zoneDepth - 0.25],
    );
  }
  for (const side of [-1, 1]) {
    push(side < 0 ? 0x367fc8 : 0x45a85f, side * 21, profile.groundY + 1.5, 0, [
      2,
      3,
      profile.footprintLengthM,
    ]);
    push(side < 0 ? 0xf5c83f : 0xe84d42, 0, profile.groundY + 1.5, side * 47, [
      profile.footprintWidthM,
      3,
      2,
    ]);
  }

  // Five stepped turrets and the published five-metre slide stay unmistakably
  // cubic while preserving the day model's placement and colour hierarchy.
  for (const [index, [localX, localZ]] of [
    [-17, -42],
    [15.5, -39],
    [-17.5, 20],
    [16, 13],
    [15, 37],
  ].entries()) {
    push(
      colors[(index + 2) % colors.length],
      localX,
      profile.groundY + 3,
      localZ,
      [4.5, 5, 4.5],
    );
    push(
      colors[(index + 5) % colors.length],
      localX,
      profile.groundY + 6,
      localZ,
      [5.5, 1, 5.5],
    );
    push(
      colors[(index + 5) % colors.length],
      localX,
      profile.groundY + 7,
      localZ,
      [3.2, 1, 3.2],
    );
    push(
      colors[(index + 5) % colors.length],
      localX,
      profile.groundY + 8,
      localZ,
      [1.4, 1, 1.4],
    );
  }
  for (let step = 0; step < 5; step += 1) {
    push(
      step % 2 === 0 ? 0x45a85f : 0xf5c83f,
      -10.5,
      profile.groundY + 1 + step * 0.5,
      -23 - step * 4.2,
      [14, 1 + step, 4.1],
    );
  }
  for (let row = 0; row < 3; row += 1) {
    for (let column = 0; column < 5; column += 1) {
      push(
        colors[(row + column) % 3],
        -12 + column * 5.8,
        profile.groundY + 2,
        6 + row * 5.2,
        [1.5, 3, 1.5],
      );
    }
  }
  for (const [localX, localZ] of [
    [-8, -10],
    [-3, -5],
    [-8, 0],
    [-13, -5],
  ] as const) {
    push(0xf5c83f, localX, profile.groundY + 1.4, localZ, [3, 1.8, 3]);
  }
  // The block entrance shares the smooth model's east-facing end placement;
  // it must not rotate back into the B96 when mobile detail is selected.
  for (const localX of [-4, 4]) {
    push(0xe84d42, localX, profile.groundY + 2, 47.3, [2, 4, 2]);
  }
  push(0xe84d42, 0, profile.groundY + 5, 47.3, [10, 2, 2]);
  push(0x8d62bd, 10, profile.groundY + 2, 53.2, [9, 4, 5]);

  const writer = instancedBoxes("Voxel FUNBOX event park", blocks.length);
  for (const block of blocks) {
    writer.write(
      new Vector3(...block.position),
      new Vector3(...block.size),
      new Color(block.color),
      profile.rotationY,
    );
  }
  writer.mesh.instanceMatrix.needsUpdate = true;
  if (writer.mesh.instanceColor) writer.mesh.instanceColor.needsUpdate = true;
  writer.mesh.frustumCulled = false;
  writer.mesh.userData.architecturalProfile = profile;
  writer.mesh.userData.sourceRole = "temporary-event-presentation";
  return writer.mesh;
}

export function createMinecraftVoxelWorld(
  payload: VoxelPayload,
  toneLookup?: ColumnToneLookup | null,
  tunnel?: TunnelPortalCourseInput | null,
  options: MinecraftVoxelWorldOptions = {},
): Group {
  const group = new Group();
  group.name = "Minecraft voxel world (LoD2 + OSM + official tree points)";
  const mobileDetail = options.detailProfile === "mobile";
  const cell = payload.cell_m;
  // Buildings/trees carry ABSOLUTE cell indices; ground runs are grid
  // offsets (see the payload origin note): cell (x_idx, z_idx) spans
  // world x in [x_idx*cell, x_idx*cell + cell).
  const worldXAbs = (xIdx: number, span = 1): number =>
    (xIdx + span / 2) * cell;
  const worldZAbs = (zIdx: number): number => (zIdx + 0.5) * cell;
  const center = new Vector3();
  const size = new Vector3();
  const insideTunnelApproach = tunnel
    ? createTunnelPortalApproachTester(tunnel, cell / Math.SQRT2)
    : null;
  group.add(createMinecraftExtrapolatedWorld());
  group.add(
    createGroundSlabs(payload, "Voxel ground runs", CLASS_SHADES, {
      // The northern harbour staircase below is rebuilt from the same exact
      // predicate in one block-native detail mesh. Suppressing it here first
      // prevents coincident DGM slabs and Schrägufer blocks from flickering.
      skipAtWorld: (x, z) =>
        Boolean(
          insideTunnelApproach?.(x, z) ||
          isNorthernHumboldthafenReplacementCell(x, z),
        ),
      skipBridgeAtWorld: isBundestagSpreeBridgeGroundCell,
    }),
  );
  group.add(createMinecraftHumboldthafenDetails(payload));
  group.add(createMinecraftArchitecturalLandmarks());
  group.add(createMinecraftPariserPlatzArchitecture());
  group.add(createMinecraftTipiAmKanzleramt());
  group.add(createMinecraftInvalidenfriedhofDetails());
  group.add(createMinecraftBrechtMemorial());
  group.add(createTiergartenLiteraryMemorialsMinecraft());
  group.add(createWagnerMemorialMinecraft());
  group.add(
    createMoabitPrisonMemorialParkMinecraft(options.detailProfile ?? "full"),
  );
  group.add(
    createWeidendammerBridgeMinecraft(
      options.detailProfile ?? "full",
      payload.water_top_y_m,
    ),
  );
  group.add(createMinecraftHamburgerBahnhofRecognition());
  group.add(
    createMinecraftSocialCourtRecognition(options.detailProfile ?? "full"),
  );
  group.add(createMinecraftBerlinModernRecognition());
  group.add(createMinecraftEinzEuropaplatzRecognition());
  group.add(createMinecraftUpbeatRecognition());
  group.add(createMinecraftFunboxRecognition());
  group.add(createMinecraftHistoricParkBridges(worldGroundSampler(payload)));

  const buildingColumns = decodeVoxelBuildingColumns(payload);
  const visibleBuildingColumns = buildingColumns
    .filter(
      ([xIdx, zIdx, y0dm, y1dm]) =>
        !wagnerMemorialVoxelReplacementAt(
          worldXAbs(xIdx),
          worldZAbs(zIdx),
          (y1dm - y0dm) / 10,
          y0dm / 10,
        ) &&
        !isFalseSintiRomaVoxelColumn(
          worldXAbs(xIdx),
          worldZAbs(zIdx),
          (y1dm - y0dm) / 10,
        ) &&
        !isFalseBundestagSpreeBridgeVoxelColumn(
          worldXAbs(xIdx),
          worldZAbs(zIdx),
          (y1dm - y0dm) / 10,
        ) &&
        !isCompleteRecognitionVoxelColumn(worldXAbs(xIdx), worldZAbs(zIdx)) &&
        (!insideTunnelApproach ||
          !insideTunnelApproach(worldXAbs(xIdx), worldZAbs(zIdx))),
    )
    .map(([xIdx, zIdx, y0dm, y1dm, classId]): VoxelBuildingColumn => {
      const sourceTopY = y1dm / 10;
      const clippedTopY = minecraftArchitecturalVoxelTopAt(
        worldXAbs(xIdx),
        worldZAbs(zIdx),
        sourceTopY,
        cell,
      );
      const clippedTopDm =
        clippedTopY < sourceTopY - 1e-6 ? clippedTopY * 10 : y1dm;
      return [xIdx, zIdx, y0dm, Math.max(y0dm, clippedTopDm), classId];
    })
    .filter(([, , y0dm, y1dm]) => y1dm > y0dm);

  const buildingLayerCount = visibleBuildingColumns.reduce(
    (count, [xIdx, zIdx, y0dm, y1dm]) => {
      const worldX = worldXAbs(xIdx);
      const worldZ = worldZAbs(zIdx);
      const recognitionArea = voxelRecognitionAreaAt(worldX, worldZ);
      const roofTopY =
        recognitionArea?.name === "Rieckhallen"
          ? RIECKHALLEN_PROFILE.minecraftRoofTopY
          : y1dm / 10;
      const height = Math.max(cell, roofTopY - y0dm / 10);
      const heroSource = isMinecraftHeroSourceCourseArea(recognitionArea);
      if (mobileDetail && !heroSource) {
        return count + 1;
      }
      const capHeight = height > 5 ? 1 : 0;
      const plinthHeight = height > 8 ? 1 : 0;
      const bodyHeight = height - capHeight - plinthHeight;
      const bodyCourseCount = heroSource
        ? Math.max(
            1,
            Math.ceil(bodyHeight / MINECRAFT_HERO_SOURCE_COURSE_MAX_M),
          )
        : 1;
      return (
        count +
        bodyCourseCount +
        (plinthHeight > 0 ? 1 : 0) +
        (capHeight > 0 ? 1 : 0)
      );
    },
    0,
  );
  const buildings = instancedBoxes(
    "Voxel building columns",
    buildingLayerCount,
  );
  const tonePaint = new Color();
  for (const [xIdx, zIdx, y0dm, y1dm, classId] of visibleBuildingColumns) {
    const className = payload.classes[classId] ?? "concrete";
    const shades = CLASS_SHADES[className] ?? FALLBACK_SHADES;
    const y0 = y0dm / 10;
    const worldX = worldXAbs(xIdx);
    const worldZ = worldZAbs(zIdx);
    const recognitionArea = voxelRecognitionAreaAt(worldX, worldZ);
    const roofTopY =
      recognitionArea?.name === "Rieckhallen"
        ? RIECKHALLEN_PROFILE.minecraftRoofTopY
        : y1dm / 10;
    const height = Math.max(cell, roofTopY - y0);
    const heroSource = isMinecraftHeroSourceCourseArea(recognitionArea);
    // Real building colour when the prism payload knows this footprint;
    // whole buildings read as one hue (no checkerboard), the class
    // shades stay as fallback for unknown columns.
    const tone = toneLookup?.(worldX, worldZ) ?? recognitionArea?.tone ?? null;
    const facade =
      tone !== null
        ? tonePaint.setHex(tone).clone()
        : shadeFor(shades, xIdx, zIdx, Math.round(height / cell));
    if (mobileDetail && !heroSource) {
      center.set(worldX, y0 + height / 2, worldZ);
      size.set(cell, height, cell);
      buildings.write(center, size, facade);
      continue;
    }
    // A palette-native plinth/body/cap stack reads as deliberate block
    // architecture. The former multiplyScalar roof invented off-palette dark
    // colours and produced muddy roofs rather than Minecraft materials.
    const layers = minecraftBuildingLayerTones(
      tone === KOLLHOFF_TOWER_PROFILE.minecraftClinkerTone
        ? "clinker"
        : className,
    );
    const capHeight = height > 5 ? 1 : 0;
    const plinthHeight = height > 8 ? 1 : 0;
    const bodyHeight = height - capHeight - plinthHeight;
    if (plinthHeight > 0) {
      center.set(worldX, y0 + plinthHeight / 2, worldZ);
      size.set(cell, plinthHeight, cell);
      buildings.write(center, size, tonePaint.setHex(layers.plinth).clone());
    }
    const bodyCourseCount = heroSource
      ? Math.max(1, Math.ceil(bodyHeight / MINECRAFT_HERO_SOURCE_COURSE_MAX_M))
      : 1;
    const bodyCourseHeight = bodyHeight / bodyCourseCount;
    for (let course = 0; course < bodyCourseCount; course += 1) {
      center.set(
        worldX,
        y0 + plinthHeight + (course + 0.5) * bodyCourseHeight,
        worldZ,
      );
      // Horizontal cells already keep a 12 cm mortar line. A smaller 8 cm
      // vertical joint makes the retained mass visibly course-built without
      // changing its measured envelope or pedestrian collision contract.
      size.set(
        cell,
        bodyCourseCount > 1
          ? Math.max(0.08, bodyCourseHeight - 0.08)
          : bodyCourseHeight,
        cell,
      );
      buildings.write(center, size, facade);
    }
    if (capHeight > 0) {
      center.set(worldX, y0 + height - capHeight / 2, worldZ);
      size.set(cell, capHeight, cell);
      buildings.write(center, size, tonePaint.setHex(layers.cap).clone());
    }
  }
  group.add(buildings.mesh);

  // Window cells on exterior faces: every ~4 m storey of a column face
  // that no neighbouring column covers gets a pale portrait pane. Hero
  // envelopes yield to their referenced recognition fenestration instead of
  // receiving a second grid of generic square holes.
  if (!mobileDetail) {
    const columnTops = new Map<number, number>();
    const columnKey = (x: number, z: number): number => x * 65536 + z;
    for (const [xIdx, zIdx, , y1dm] of visibleBuildingColumns) {
      const key = columnKey(xIdx, zIdx);
      columnTops.set(key, Math.max(columnTops.get(key) ?? -1e9, y1dm / 10));
    }
    type WindowFace = {
      color: Color;
      nx: number;
      nz: number;
      x: number;
      y: number;
      z: number;
    };
    const faces: WindowFace[] = [];
    const glass = new Color(VOXEL_WINDOW_GLASS);
    const glassPale = new Color(VOXEL_WINDOW_GLASS_PALE);
    const teal = new Color(VOXEL_WINDOW_TEAL);
    for (const [xIdx, zIdx, y0dm, y1dm, classId] of visibleBuildingColumns) {
      if (WINDOWLESS_CLASSES.has(payload.classes[classId] ?? "")) {
        continue;
      }
      if (voxelRecognitionAreaAt(worldXAbs(xIdx), worldZAbs(zIdx))) {
        continue;
      }
      const top = y1dm / 10;
      for (const [dx, dz] of [
        [1, 0],
        [-1, 0],
        [0, 1],
        [0, -1],
      ] as const) {
        const neighbourTop = columnTops.get(columnKey(xIdx + dx, zIdx + dz));
        const faceX = worldXAbs(xIdx) + (dx * cell) / 2 + dx * 0.08;
        const faceZ = worldZAbs(zIdx) + (dz * cell) / 2 + dz * 0.08;
        if (voxelRecognitionAreaAt(faceX, faceZ)) {
          continue;
        }
        // Storey-banded window rows: every column face carries its glass
        // on the SAME storey grid, so the facade reads as designed rows
        // rather than randomly punched holes.
        const base = y0dm / 10;
        const firstRow = Math.ceil((base + 2) / cell) * cell;
        for (let yCenter = firstRow; yCenter + 1.2 <= top; yCenter += cell) {
          if (neighbourTop !== undefined && neighbourTop >= yCenter + 1) {
            continue;
          }
          // Two glass tones alternate along the row for gentle block
          // variety; a teal accent every fourth bay keeps it lively.
          const bay = Math.abs(xIdx + zIdx);
          const color =
            bay % 4 === 0 ? teal : bay % 2 === 0 ? glass : glassPale;
          faces.push({
            color,
            nx: dx,
            nz: dz,
            x: faceX,
            y: yCenter,
            z: faceZ,
          });
        }
      }
    }
    if (faces.length > 0) {
      const panes = new InstancedMesh(
        new PlaneGeometry(1, 1),
        new MeshBasicMaterial({ color: 0xffffff, side: DoubleSide }),
        faces.length,
      );
      panes.name = "Voxel facade windows";
      const matrix = new Matrix4();
      faces.forEach((face, index) => {
        // Plane spans the face's tangent; dir = up × normal in the plane.
        const dirX = -face.nz;
        const dirZ = face.nx;
        matrix.set(
          dirX * VOXEL_WINDOW_WIDTH_M,
          0,
          face.nx,
          face.x,
          0,
          VOXEL_WINDOW_HEIGHT_M,
          0,
          face.y,
          dirZ * VOXEL_WINDOW_WIDTH_M,
          0,
          face.nz,
          face.z,
          0,
          0,
          0,
          1,
        );
        panes.setMatrixAt(index, matrix);
        panes.setColorAt(index, face.color);
      });
      panes.instanceMatrix.needsUpdate = true;
      if (panes.instanceColor) {
        panes.instanceColor.needsUpdate = true;
      }
      panes.frustumCulled = false;
      group.add(panes);
    }
  }

  const visibleTrees = decodeVoxelTreeBlocks(payload).filter(
    ([xIdx, zIdx]) =>
      !isChancelleryExtensionConstructionPoint(
        worldXAbs(xIdx),
        worldZAbs(zIdx),
      ) &&
      !isHolocaustMinecraftProtectedAt(
        worldXAbs(xIdx),
        worldZAbs(zIdx),
        cell * 1.1,
      ) &&
      (!insideTunnelApproach ||
        !insideTunnelApproach(worldXAbs(xIdx), worldZAbs(zIdx), cell * 1.1)),
  );
  const trunks = instancedBoxes("Voxel tree trunks", visibleTrees.length);
  const crowns = instancedBoxes("Voxel tree crowns", visibleTrees.length * 2);
  for (const [xIdx, zIdx, y0dm, hdm] of visibleTrees) {
    const y0 = y0dm / 10;
    const height = Math.max(cell, hdm / 10);
    const trunkHeight = Math.max(cell / 2, height - cell * 1.5);
    const species = Math.abs(xIdx * 7 + zIdx * 13) % 5;
    center.set(worldXAbs(xIdx), y0 + trunkHeight / 2, worldZAbs(zIdx));
    size.set(cell * 0.45, trunkHeight, cell * 0.45);
    // Every fifth tree is a birch (pale trunk), like a mixed park.
    trunks.write(
      center,
      size,
      species === 0
        ? new Color(0xd6dfe0)
        : shadeFor(TRUNK_SHADES, xIdx, zIdx, 1),
    );
    const crownHeight = cell * 1.9;
    center.set(
      worldXAbs(xIdx),
      y0 + trunkHeight + crownHeight / 2,
      worldZAbs(zIdx),
    );
    size.set(cell * 2.2, crownHeight, cell * 2.2);
    crowns.write(center, size, shadeFor(LEAF_SHADES, xIdx, zIdx, 2));
    // Every third tree stacks a smaller crown — the spruce silhouette.
    if (species === 1 || species === 3) {
      center.set(
        worldXAbs(xIdx),
        y0 + trunkHeight + crownHeight + cell * 0.55,
        worldZAbs(zIdx),
      );
      size.set(cell * 1.3, cell * 1.1, cell * 1.3);
      crowns.write(center, size, shadeFor(LEAF_SHADES, xIdx, zIdx, 3));
    }
  }
  group.add(trunks.mesh);
  group.add(crowns.mesh);

  // Meadow flowers: sparse deterministic colour dots on grass runs —
  // the small-scale life real Minecraft plains have.
  if (!mobileDetail) {
    const FLOWER_TONES = [0xe6bd4c, 0xe79a61, 0xf7fbf7] as const;
    const grassClass = payload.classes.indexOf("grass");
    const groundTopY = groundTopSampler(payload);
    const flowerSpots: Array<[number, number, number]> = [];
    payload.ground_rows.forEach((row, zOffset) => {
      for (const [xStart, run, classId] of row) {
        if (classId !== grassClass) {
          continue;
        }
        for (let step = 0; step < run; step += 1) {
          const xOffset = xStart + step;
          const roll = Math.abs(xOffset * 2654435761 + zOffset * 40503) % 41;
          if (roll === 0) {
            flowerSpots.push([xOffset, zOffset, roll]);
          }
        }
      }
    });
    const flowers = instancedBoxes("Voxel meadow flowers", flowerSpots.length);
    for (const [xOffset, zOffset] of flowerSpots) {
      const topY = groundTopY(xOffset, zOffset);
      center.set(
        worldXAbs(payload.grid.min_x_idx + xOffset),
        topY + 0.3,
        worldZAbs(payload.grid.min_z_idx + zOffset),
      );
      size.set(0.55, 0.6, 0.55);
      flowers.write(
        center,
        size,
        new Color(
          FLOWER_TONES[
            Math.abs(xOffset * 31 + zOffset * 17) % FLOWER_TONES.length
          ],
        ),
      );
    }
    group.add(flowers.mesh);
  }

  for (const child of group.children) {
    if (child instanceof InstancedMesh) {
      child.instanceMatrix.needsUpdate = true;
      if (child.instanceColor) {
        child.instanceColor.needsUpdate = true;
      }
      child.frustumCulled = false;
    }
  }
  return group;
}
