import {
  BoxGeometry,
  Color,
  DoubleSide,
  Group,
  InstancedMesh,
  Matrix4,
  MeshBasicMaterial,
  PlaneGeometry,
  Vector3,
  MeshStandardMaterial,
} from "three";

import { MINECRAFT_BUILDING_PALETTE } from "./visual-modes/minecraft/palette";
import { RIECKHALLEN_PROFILE } from "./ExpandedCityDetails";
import {
  AXIS_FROM,
  AXIS_TO,
  DATA_EAST_M,
  EXTRAPOLATED_MARGIN_M,
  VISIBLE_RADIUS_M,
  extrapolatedEnvelopeBounds,
  extrapolatedMarginBands,
} from "./worldEnvelope";

/**
 * True voxel world for the Minecraft mode: the city as axis-aligned
 * blocks generated by `isometric_berlin.generation.build_minecraft_voxels`
 * from surveyed LoD2 footprints + measured heights, OSM water/roads and
 * the official tree points. Rendered as a handful of InstancedMeshes
 * (one box per building column / ground run / tree part) so the whole
 * world stays at a few draw calls and well below photogrammetry-tier
 * triangle counts — deliberately "eckig, klotzig, blockig".
 */
export type VoxelPayload = {
  schema_version: number;
  cell_m: number;
  classes: string[];
  grid: { cols: number; min_x_idx: number; min_z_idx: number; rows: number };
  /** Coarse ground-top heights in decimetres, row-major at stride_cells. */
  ground_height: {
    cols: number;
    rows: number;
    stride_cells: number;
    y_dm: number[];
  };
  /** rows[z_offset] = [x_start_offset, run_length, classId][] (grid offsets). */
  ground_rows: Array<Array<[number, number, number]>>;
  /** [x_idx, z_idx, y0_dm, y1_dm, classId] with ABSOLUTE cell indices. */
  buildings: Array<[number, number, number, number, number]>;
  /** [x_idx, z_idx, y0_dm, height_dm] with ABSOLUTE cell indices. */
  trees: Array<[number, number, number, number]>;
  water_top_y_m: number;
};

export const VOXEL_WORLD_FILE = "minecraft-voxels.json";
const GROUND_SLAB_M = 3;
/**
 * Spree/Kanal water table (fallback for payloads without the field).
 * The banks sit at ~4.2 m, so the river runs in a real cut about 5.3 m
 * below the city instead of level with the streets.
 */
export const WATER_TOP_Y = -1.15;

// Every shade comes from MINECRAFT_PALETTE (palette.ts); small
// deterministic per-instance jitter between shades is what gives the
// classic Minecraft block-noise without any texture.
// Owner note "bessere Farben im Minecraft mode": each class now uses
// two or three CLOSE shades (gentle block-noise instead of the harsh
// checkerboard), greens follow classic plains grass/oak leaves, water is
// the clear Minecraft blue and roads read as dark slate, not void-black.
const CLASS_SHADES: Record<string, readonly number[]> = {
  asphalt: [0x40515c, 0x34443a],
  concrete: [0xd4d4b7, 0xf3efd0],
  glass: [0x72c5d2, 0xa4dfe2],
  grass: [0x74b043, 0x5d9634, 0x74b043],
  plazaBrick: [0x994a35, 0x715b4a],
  // A constructed basin is the same blue as the river, but its cells keep
  // the local ground height instead of the Spree table — an ornamental
  // basin sits on the ground it was built into, not 6 m below it.
  basin: [0x3f76e4, 0x2e5aa8],
  // Bridge decks over the Spree/Humboldthafen read as stone blocks.
  bridge: [0x8e9a9e, 0xa4aa91],
  sandstone: [0xe8d1ae, 0xf5e3c5],
  // Bare concrete for freestanding walls: no interior, so no windows.
  wall: [0xb8b4a8, 0xc7c3b6],
  water: [0x3f76e4, 0x2e5aa8],
};
/** Column classes that are solid structures rather than inhabited floors. */
const WINDOWLESS_CLASSES: ReadonlySet<string> = new Set(["wall"]);
const FALLBACK_SHADES: readonly number[] = CLASS_SHADES.concrete;
const TRUNK_SHADES: readonly number[] = [0x704a2d];
const LEAF_SHADES: readonly number[] = [0x4c7f28, 0x5d9634];
// Facade window cells read as MINECRAFT GLASS — light, glassy blocks
// from the master palette. The former dark slate (0x40515c) punched
// black holes into every facade ("hässliche schwarze Fenster").
const VOXEL_WINDOW_GLASS = 0xa4dfe2;
const VOXEL_WINDOW_GLASS_PALE = 0xd6dfe0;
const VOXEL_WINDOW_TEAL = 0x72c5d2;
export const VOXEL_WINDOW_WIDTH_M = 1.5;
export const VOXEL_WINDOW_HEIGHT_M = 2.75;

/** LoD2-tower-derived centre of the Hamburger Bahnhof entrance facade. */
export const HAMBURGER_BAHNHOF_VOXEL_FACADE = {
  axis: [0.8673, -0.4978] as const,
  center: [72.855, -1043.07] as const,
  groundY: 8,
  normal: [0.4978, 0.8673] as const,
  rotationDegrees: 30,
} as const;

export type VoxelRecognitionArea = {
  center: readonly [number, number];
  depthM: number;
  name: string;
  paddingM: number;
  rotationDegrees: number;
  tone: number;
  widthM: number;
};

// Metric envelopes copied from the versioned architectural signatures in
// scene.json. The true voxel columns remain untouched; only their generic
// square-window overlay yields to the more accurate recognition model.
const RECOGNITION_AREAS: readonly VoxelRecognitionArea[] = [
  {
    center: [317.729, 40.477],
    depthM: 138,
    name: "Reichstag",
    paddingM: 10,
    rotationDegrees: -1.676,
    tone: 0xd4d4b7,
    widthM: 100,
  },
  {
    center: [-220.236, -145.806],
    depthM: 102.074,
    name: "Bundeskanzleramt",
    paddingM: 6,
    rotationDegrees: -1.337,
    // Pale cool concrete, not the warm cream 0xf3efd0 this pin used to
    // carry. Cream has 31 units more green than blue, and once the voxel
    // rig multiplied it the Chancellery — white concrete in reality —
    // rendered as a khaki-yellow block across its whole 343 m envelope.
    tone: 0xd6dfe0,
    widthM: 342.676,
  },
  {
    center: [-119.936, -683.307],
    depthM: 200,
    name: "Berlin Hauptbahnhof",
    paddingM: 6,
    rotationDegrees: 21.82,
    tone: 0xd6dfe0,
    widthM: 341,
  },
  {
    // The head building is not a generic office facade. A dedicated stepped
    // voxel elevation below carries its two towers and arched hall front.
    center: HAMBURGER_BAHNHOF_VOXEL_FACADE.center,
    depthM: 8,
    name: "Hamburger Bahnhof",
    paddingM: 2,
    rotationDegrees: HAMBURGER_BAHNHOF_VOXEL_FACADE.rotationDegrees,
    tone: 0xe8d1ae,
    widthM: 64,
  },
  {
    // One low 281 m freight hall, not a row of alternating 8/12 m voxel
    // peaks. The payload remains the footprint authority; this envelope only
    // evens the coarse top row and suppresses generic office windows.
    center: RIECKHALLEN_PROFILE.centerWorldM,
    depthM: RIECKHALLEN_PROFILE.lengthM,
    name: "Rieckhallen",
    paddingM: 0.6,
    rotationDegrees: (RIECKHALLEN_PROFILE.rotationY * 180) / Math.PI,
    tone: 0x586b6f,
    widthM: RIECKHALLEN_PROFILE.widthM,
  },
  {
    center: [417.898, 300.453],
    depthM: 18,
    name: "Brandenburger Tor",
    paddingM: 3,
    rotationDegrees: 5.083,
    tone: 0xe8d1ae,
    widthM: 68,
  },
  {
    // OSM way/1535591727. The exact bent outline is supplied by the
    // always-visible recognition model; suppress the generic square-window
    // overlay across its bbox so Minecraft does not put a second rectangular
    // office through the coloured 2026 facade.
    center: [-300.31, -359.65],
    depthM: 73.72,
    name: "Amtssitz am Spreebogen",
    paddingM: 4,
    rotationDegrees: 0,
    tone: 0xbba087,
    widthM: 92.9,
  },
];

export function voxelRecognitionAreaAt(
  x: number,
  z: number,
): VoxelRecognitionArea | null {
  for (const area of RECOGNITION_AREAS) {
    const radians = (area.rotationDegrees * Math.PI) / 180;
    const cosine = Math.cos(radians);
    const sine = Math.sin(radians);
    const dx = x - area.center[0];
    const dz = z - area.center[1];
    const localX = dx * cosine - dz * sine;
    const localZ = dx * sine + dz * cosine;
    if (
      Math.abs(localX) <= area.widthM / 2 + area.paddingM &&
      Math.abs(localZ) <= area.depthM / 2 + area.paddingM
    ) {
      return area;
    }
  }
  return null;
}

function shadeFor(
  shades: readonly number[],
  xIdx: number,
  zIdx: number,
  salt: number,
): Color {
  const pick = Math.abs(xIdx * 31 + zIdx * 17 + salt * 7) % shades.length;
  return new Color(shades[pick]);
}

function voxelMaterial(emissive = 0x3d3d3d): MeshStandardMaterial {
  return new MeshStandardMaterial({
    color: 0xffffff,
    // A small neutral emissive floor lifts the shadow faces so block
    // colours stay readable all around, like Minecraft's flat light.
    // The drawn city passes 0 — its ground must not self-glow.
    emissive,
    flatShading: true,
    metalness: 0,
    roughness: 1,
  });
}

type InstanceWriter = {
  mesh: InstancedMesh;
  write: (center: Vector3, size: Vector3, color: Color) => void;
};

function instancedBoxes(
  name: string,
  count: number,
  emissive?: number,
): InstanceWriter {
  const mesh = new InstancedMesh(
    new BoxGeometry(1, 1, 1),
    voxelMaterial(emissive),
    Math.max(1, count),
  );
  mesh.name = name;
  mesh.count = 0;
  const matrix = new Matrix4();
  return {
    mesh,
    write: (center, size, color) => {
      const index = mesh.count;
      matrix.makeScale(size.x, size.y, size.z);
      matrix.setPosition(center.x, center.y, center.z);
      mesh.setMatrixAt(index, matrix);
      mesh.setColorAt(index, color);
      mesh.count = index + 1;
    },
  };
}

/**
 * Sample the payload's coarse interpolated terrain grid at grid offsets.
 */
export function groundTopSampler(
  payload: VoxelPayload,
): (xOffset: number, zOffset: number) => number {
  const heights = payload.ground_height;
  return (xOffset, zOffset) => {
    const col = Math.min(
      heights.cols - 1,
      Math.floor(xOffset / heights.stride_cells),
    );
    const row = Math.min(
      heights.rows - 1,
      Math.floor(zOffset / heights.stride_cells),
    );
    return (heights.y_dm[row * heights.cols + col] ?? 40) / 10;
  };
}

/**
 * Per-column real-colour lookup: point-in-footprint against the LoD2
 * prism payload, each building's sampled tone snapped to the nearest
 * Minecraft palette entry. Kills the one-colour-city ("einfarbig")
 * while staying strictly inside the authored block palette.
 */
export type ColumnToneLookup = (x: number, z: number) => number | null;

type TonedPrism = {
  hex: number;
  maxX: number;
  maxZ: number;
  minX: number;
  minZ: number;
  ring: Array<[number, number]>;
};

export function buildColumnToneLookup(prisms: {
  buildings: Array<{
    id?: string;
    ring: number[][];
    tone?: [number, number, number];
  }>;
}): ColumnToneLookup {
  // Chroma carries identity, brightness does not. Plain RGB distance let a
  // near-neutral concrete sample land on the sandstone creams simply
  // because they are the brightest entries — which is why the Chancellery,
  // white concrete in reality, rendered as a khaki-yellow block. Matching
  // on (luma, r−luma, b−luma) with the two chroma axes weighted four times
  // keeps a grey building grey and a warm building warm.
  const CHROMA_WEIGHT = 4;
  const luminance = (r: number, g: number, b: number): number =>
    0.2126 * r + 0.7152 * g + 0.0722 * b;
  const palette = MINECRAFT_BUILDING_PALETTE.map((hex) => {
    const r = (hex >> 16) & 255;
    const g = (hex >> 8) & 255;
    const b = hex & 255;
    const y = luminance(r, g, b);
    return { b, cb: b - y, cr: r - y, g, hex, r, y };
  });
  const snap = (tone: [number, number, number]): number => {
    // Lighten and desaturate the raw photo sample toward the drawn
    // city's bright band BEFORE matching ("heller"), so a building that
    // is pale cream by day is not a dark block in Minecraft.
    const luma = luminance(tone[0], tone[1], tone[2]);
    // Bright band, matching the drawn city's ivory register: the old floor
    // of 150 left most Berlin samples (median luma 111) sitting on the two
    // darkest stone entries, which is the grey-city look the owner rejected.
    const target = Math.min(236, Math.max(168, luma));
    const scale = target / Math.max(luma, 1);
    const lifted: [number, number, number] = [
      Math.min(255, tone[0] * scale),
      Math.min(255, tone[1] * scale),
      Math.min(255, tone[2] * scale),
    ];
    const liftedLuma = luminance(lifted[0], lifted[1], lifted[2]);
    const liftedCr = lifted[0] - liftedLuma;
    const liftedCb = lifted[2] - liftedLuma;
    let best = palette[0].hex;
    let bestDistance = Number.POSITIVE_INFINITY;
    for (const entry of palette) {
      const distance =
        (liftedLuma - entry.y) ** 2 +
        CHROMA_WEIGHT *
          ((liftedCr - entry.cr) ** 2 + (liftedCb - entry.cb) ** 2);
      if (distance < bestDistance) {
        bestDistance = distance;
        best = entry.hex;
      }
    }
    return best;
  };
  const BUCKET = 32;
  const buckets = new Map<string, TonedPrism[]>();
  for (const building of prisms.buildings) {
    if (!building.tone || building.ring.length < 3) {
      continue;
    }
    const ring = building.ring.map(
      ([x, z]) => [x / 10, z / 10] as [number, number],
    );
    const xs = ring.map(([x]) => x);
    const zs = ring.map(([, z]) => z);
    const toned: TonedPrism = {
      hex: snap(building.tone),
      maxX: Math.max(...xs),
      maxZ: Math.max(...zs),
      minX: Math.min(...xs),
      minZ: Math.min(...zs),
      ring,
    };
    for (
      let bx = Math.floor(toned.minX / BUCKET);
      bx <= Math.floor(toned.maxX / BUCKET);
      bx += 1
    ) {
      for (
        let bz = Math.floor(toned.minZ / BUCKET);
        bz <= Math.floor(toned.maxZ / BUCKET);
        bz += 1
      ) {
        const key = `${bx},${bz}`;
        const list = buckets.get(key);
        if (list) {
          list.push(toned);
        } else {
          buckets.set(key, [toned]);
        }
      }
    }
  }
  const inside = (
    x: number,
    z: number,
    ring: Array<[number, number]>,
  ): boolean => {
    let odd = false;
    for (let i = 0, j = ring.length - 1; i < ring.length; j = i, i += 1) {
      const [xi, zi] = ring[i];
      const [xj, zj] = ring[j];
      if (zi > z !== zj > z && x < ((xj - xi) * (z - zi)) / (zj - zi) + xi) {
        odd = !odd;
      }
    }
    return odd;
  };
  return (x, z) => {
    const recognitionArea = voxelRecognitionAreaAt(x, z);
    if (recognitionArea) {
      return recognitionArea.tone;
    }
    const list = buckets.get(
      `${Math.floor(x / BUCKET)},${Math.floor(z / BUCKET)}`,
    );
    if (!list) {
      return null;
    }
    for (const toned of list) {
      if (
        x >= toned.minX &&
        x <= toned.maxX &&
        z >= toned.minZ &&
        z <= toned.maxZ &&
        inside(x, z, toned.ring)
      ) {
        return toned.hex;
      }
    }
    return null;
  };
}

/**
 * World-coordinate ground sampler: metres in, terrain-top metres out,
 * null outside the surveyed grid.
 */
export function worldGroundSampler(
  payload: VoxelPayload,
): (x: number, z: number) => number | null {
  const sample = groundTopSampler(payload);
  const cell = payload.cell_m;
  const { cols, min_x_idx, min_z_idx, rows } = payload.grid;
  return (x, z) => {
    const xOffset = x / cell - min_x_idx;
    const zOffset = z / cell - min_z_idx;
    if (xOffset < 0 || zOffset < 0 || xOffset >= cols || zOffset >= rows) {
      return null;
    }
    return sample(xOffset, zOffset);
  };
}

/**
 * Build the run-length ground slabs as one InstancedMesh. Shared between
 * the Minecraft voxel world and the drawn isometric city (which reuses
 * the same surveyed ground/water/road classes with its own palette).
 */
export function createGroundSlabs(
  payload: VoxelPayload,
  name: string,
  shadeMap: Record<string, readonly number[]>,
  options?: {
    bridgeDecks?: boolean;
    emissive?: number;
    skipBridge?: boolean;
    skipWater?: boolean;
  },
): InstancedMesh {
  const cell = payload.cell_m;
  const { min_x_idx, min_z_idx } = payload.grid;
  const worldXAbs = (xIdx: number, span = 1): number =>
    (xIdx + span / 2) * cell;
  const worldZAbs = (zIdx: number): number => (zIdx + 0.5) * cell;
  const groundTopY = groundTopSampler(payload);
  const groundRunCount = payload.ground_rows.reduce(
    (sum, row) => sum + row.length,
    0,
  );
  const ground = instancedBoxes(name, groundRunCount, options?.emissive);
  const center = new Vector3();
  const size = new Vector3();
  payload.ground_rows.forEach((row, zOffset) => {
    for (const [xStart, run, classId] of row) {
      const className = payload.classes[classId] ?? "grass";
      if (
        options?.skipWater &&
        (className === "water" || className === "basin")
      ) {
        continue;
      }
      // The drawn city builds real elevated bridge structures instead.
      if (options?.skipBridge && className === "bridge") {
        continue;
      }
      const shades = shadeMap[className] ?? shadeMap.grass ?? FALLBACK_SHADES;
      const topY =
        className === "water"
          ? (payload.water_top_y_m ?? WATER_TOP_Y)
          : groundTopY(xStart + run / 2, zOffset);
      // Real bridge decks (drawn city): a thin plate at bank level with
      // open air beneath, so the river visibly flows under the bridge
      // instead of the deck being ironed flat onto the water.
      const slabHeight =
        options?.bridgeDecks && className === "bridge" ? 1.1 : GROUND_SLAB_M;
      center.set(
        worldXAbs(min_x_idx + xStart, run),
        topY - slabHeight / 2,
        worldZAbs(min_z_idx + zOffset),
      );
      size.set(run * cell, slabHeight, cell);
      ground.write(center, size, shadeFor(shades, xStart, zOffset, run));
    }
  });
  return ground.mesh;
}

type ExtrapolatedBlock = {
  color: number;
  position: [number, number, number];
  size: [number, number, number];
};

function addTiledBand(
  blocks: ExtrapolatedBlock[],
  band: readonly [number, number, number, number],
  toneOffset: number,
  centerY = 0.8,
  height = 2.6,
): void {
  const [centerX, centerZ, sizeX, sizeZ] = band;
  const tileM = 80;
  const minX = centerX - sizeX / 2;
  const minZ = centerZ - sizeZ / 2;
  const columns = Math.ceil(sizeX / tileM);
  const rows = Math.ceil(sizeZ / tileM);
  for (let row = 0; row < rows; row += 1) {
    const z0 = minZ + row * tileM;
    const depth = Math.min(tileM, minZ + sizeZ - z0);
    for (let column = 0; column < columns; column += 1) {
      const x0 = minX + column * tileM;
      const width = Math.min(tileM, minX + sizeX - x0);
      blocks.push({
        color: (column + row + toneOffset) % 2 === 0 ? 0x74b043 : 0x91bd59,
        position: [x0 + width / 2, centerY, z0 + depth / 2],
        size: [width, height, depth],
      });
    }
  }
}

function addBlockRoad(
  blocks: ExtrapolatedBlock[],
  from: readonly [number, number],
  to: readonly [number, number],
  widthM: number,
): void {
  const cellM = 4;
  const dx = to[0] - from[0];
  const dz = to[1] - from[1];
  const length = Math.hypot(dx, dz);
  const ux = dx / length;
  const uz = dz / length;
  const nx = -uz;
  const nz = ux;
  const alongCount = Math.ceil(length / cellM);
  const acrossCount = Math.ceil(widthM / cellM);
  for (let along = 0; along < alongCount; along += 1) {
    const distance = Math.min(length, along * cellM + cellM / 2);
    for (let across = 0; across < acrossCount; across += 1) {
      const lateral = (across + 0.5) * cellM - (acrossCount * cellM) / 2;
      blocks.push({
        color: (along + across) % 7 === 0 ? 0x40515c : 0x202923,
        position: [
          from[0] + ux * distance + nx * lateral,
          0.9,
          from[1] + uz * distance + nz * lateral,
        ],
        size: [cellM, 2.8, cellM],
      });
    }
  }
}

/**
 * Block counterpart of the versioned drawn surround. The official voxel
 * payload remains untouched; everything outside its grid is explicitly
 * marked as an extrapolated presentation layer.
 */
export function createMinecraftExtrapolatedWorld(): Group {
  const group = new Group();
  group.name = "Minecraft extrapolated radius surround";
  group.userData.extrapolated = true;
  group.userData.visibleRadiusM = VISIBLE_RADIUS_M;

  const groundBlocks: ExtrapolatedBlock[] = [];
  const envelope = extrapolatedEnvelopeBounds();
  addTiledBand(
    groundBlocks,
    [
      (envelope.minX + envelope.maxX) / 2,
      (envelope.minZ + envelope.maxZ) / 2,
      envelope.maxX - envelope.minX,
      envelope.maxZ - envelope.minZ,
    ],
    1,
    -6,
    1,
  );
  extrapolatedMarginBands().forEach((band, index) => {
    addTiledBand(groundBlocks, band, index);
  });

  addBlockRoad(
    groundBlocks,
    [DATA_EAST_M, AXIS_FROM[1]],
    [DATA_EAST_M + EXTRAPOLATED_MARGIN_M, AXIS_FROM[1]],
    40,
  );

  const ground = instancedBoxes(
    "Voxel extrapolated ground and roads",
    groundBlocks.length,
  );
  for (const block of groundBlocks) {
    ground.write(
      new Vector3(...block.position),
      new Vector3(...block.size),
      new Color(block.color),
    );
  }
  group.add(ground.mesh);

  const columnParts: ExtrapolatedBlock[] = [
    {
      color: 0x994a35,
      position: [AXIS_TO[0], 5.6, AXIS_TO[1]],
      size: [46, 7, 46],
    },
    {
      color: 0xd4d4b7,
      position: [AXIS_TO[0], 11.6, AXIS_TO[1]],
      size: [18, 5, 18],
    },
    {
      color: 0xe8d1ae,
      position: [AXIS_TO[0], 36.1, AXIS_TO[1]],
      size: [9, 44, 9],
    },
    {
      color: 0xe6bd4c,
      position: [AXIS_TO[0], 59.6, AXIS_TO[1]],
      size: [12, 3, 12],
    },
    {
      color: 0xe6bd4c,
      position: [AXIS_TO[0], 64.1, AXIS_TO[1]],
      size: [3, 6, 3],
    },
    {
      color: 0xe6bd4c,
      position: [AXIS_TO[0], 65.2, AXIS_TO[1]],
      size: [9, 3, 1.5],
    },
    {
      color: 0xe6bd4c,
      position: [AXIS_TO[0], 68, AXIS_TO[1]],
      size: [2, 2, 2],
    },
  ];
  const column = instancedBoxes(
    "Voxel extrapolated Siegessäule",
    columnParts.length,
  );
  for (const part of columnParts) {
    column.write(
      new Vector3(...part.position),
      new Vector3(...part.size),
      new Color(part.color),
    );
  }
  group.add(column.mesh);

  for (const child of group.children) {
    if (child instanceof InstancedMesh) {
      child.instanceMatrix.needsUpdate = true;
      if (child.instanceColor) {
        child.instanceColor.needsUpdate = true;
      }
      child.frustumCulled = false;
    }
  }
  return group;
}

/**
 * One stepped, block-native front for the Hamburger Bahnhof. The surveyed
 * voxel columns remain the building mass; this single instanced overlay gives
 * that mass its actual flat head-building hierarchy without importing the
 * smooth Day/Night drawing into Minecraft mode.
 */
export function createMinecraftHamburgerBahnhofRecognition(): InstancedMesh {
  const facade = HAMBURGER_BAHNHOF_VOXEL_FACADE;
  const blocks: ExtrapolatedBlock[] = [];
  const at = (u: number, outward: number): [number, number] => [
    facade.center[0] + facade.axis[0] * u + facade.normal[0] * outward,
    facade.center[1] + facade.axis[1] * u + facade.normal[1] * outward,
  ];
  const push = (
    color: number,
    u: number,
    y: number,
    outward: number,
    size: readonly [number, number, number],
  ): void => {
    const [x, z] = at(u, outward);
    blocks.push({ color, position: [x, y, z], size: [...size] });
  };

  // A two-metre stepped facade follows the real 30 degree line. The towers
  // rise to the measured 26 m level; the main hall and wings remain lower.
  for (let u = -30; u <= 30; u += 2) {
    const tower = Math.abs(Math.abs(u) - 12) <= 2;
    const centre = Math.abs(u) <= 10;
    const top = tower ? 26 : centre ? 20 : 15;
    for (let y = facade.groundY + 1; y < facade.groundY + top; y += 2) {
      push(0xe8d1ae, u, y, -0.25, [1.82, 1.82, 1.3]);
    }
  }

  // Cornice courses remain block rows rather than smooth mouldings.
  for (let u = -30; u <= 30; u += 2) {
    const y = facade.groundY + (Math.abs(u) <= 11 ? 20 : 15);
    push(0xf3efd0, u, y, 0.48, [1.9, 0.72, 1.45]);
  }

  // Six green upper arcades, two large dark hall arches and two timber doors.
  for (const u of [-7.5, -4.5, -1.5, 1.5, 4.5, 7.5]) {
    for (const y of [14.2, 16.2, 18.2]) {
      push(0x74b043, u, facade.groundY + y, 0.86, [1.35, 1.65, 0.68]);
    }
  }
  for (const u of [-4.4, 4.4]) {
    for (const du of [-2, 0, 2]) {
      for (const y of [7.1, 9.1, 11.1]) {
        push(0x40515c, u + du, facade.groundY + y, 0.9, [1.55, 1.6, 0.7]);
      }
    }
    push(0x994a35, u, facade.groundY + 2.2, 0.96, [2.1, 4.1, 0.72]);
  }

  // Three belfry slots in each measured tower and a pale clock/rosette block.
  for (const towerU of [-11.43, 11.43]) {
    for (const du of [-1.35, 0, 1.35]) {
      push(
        0x40515c,
        towerU + du,
        facade.groundY + 23,
        0.9,
        [0.82, 2.8, 0.7],
      );
    }
    push(0xd6dfe0, towerU, facade.groundY + 18.8, 0.94, [1.7, 1.7, 0.72]);
  }

  const writer = instancedBoxes(
    "Voxel Hamburger Bahnhof recognition facade",
    blocks.length,
  );
  for (const block of blocks) {
    writer.write(
      new Vector3(...block.position),
      new Vector3(...block.size),
      new Color(block.color),
    );
  }
  writer.mesh.instanceMatrix.needsUpdate = true;
  if (writer.mesh.instanceColor) writer.mesh.instanceColor.needsUpdate = true;
  writer.mesh.frustumCulled = false;
  writer.mesh.userData.architecturalProfile = {
    lowerHallArches: 2,
    roofForm: "flat-cornice",
    towerHeightM: 26,
    upperArcades: 6,
  };
  return writer.mesh;
}

export function createMinecraftVoxelWorld(
  payload: VoxelPayload,
  toneLookup?: ColumnToneLookup | null,
): Group {
  const group = new Group();
  group.name = "Minecraft voxel world (LoD2 + OSM + official tree points)";
  const cell = payload.cell_m;
  // Buildings/trees carry ABSOLUTE cell indices; ground runs are grid
  // offsets (see the payload origin note): cell (x_idx, z_idx) spans
  // world x in [x_idx*cell, x_idx*cell + cell).
  const worldXAbs = (xIdx: number, span = 1): number =>
    (xIdx + span / 2) * cell;
  const worldZAbs = (zIdx: number): number => (zIdx + 0.5) * cell;
  const center = new Vector3();
  const size = new Vector3();
  group.add(createMinecraftExtrapolatedWorld());
  group.add(createGroundSlabs(payload, "Voxel ground runs", CLASS_SHADES));
  group.add(createMinecraftHamburgerBahnhofRecognition());

  const buildings = instancedBoxes(
    "Voxel building columns",
    payload.buildings.length * 2,
  );
  const tonePaint = new Color();
  for (const [xIdx, zIdx, y0dm, y1dm, classId] of payload.buildings) {
    const className = payload.classes[classId] ?? "concrete";
    const shades = CLASS_SHADES[className] ?? FALLBACK_SHADES;
    const y0 = y0dm / 10;
    const worldX = worldXAbs(xIdx);
    const worldZ = worldZAbs(zIdx);
    const recognitionArea = voxelRecognitionAreaAt(worldX, worldZ);
    const roofTopY =
      recognitionArea?.name === "Rieckhallen"
        ? RIECKHALLEN_PROFILE.minecraftRoofTopY
        : y1dm / 10;
    const height = Math.max(cell, roofTopY - y0);
    // Real building colour when the prism payload knows this footprint;
    // whole buildings read as one hue (no checkerboard), the class
    // shades stay as fallback for unknown columns.
    const tone = toneLookup?.(worldX, worldZ) ?? recognitionArea?.tone ?? null;
    const facade =
      tone !== null
        ? tonePaint.setHex(tone).clone()
        : shadeFor(shades, xIdx, zIdx, Math.round(height / cell));
    // Minecraft buildings wear a darker roof layer — the top block row
    // reads as roofing, like the game's slab-capped houses.
    const capHeight = height > 3 ? 1 : 0;
    center.set(worldX, y0 + (height - capHeight) / 2, worldZ);
    size.set(cell, height - capHeight, cell);
    buildings.write(center, size, facade);
    if (capHeight > 0) {
      center.set(worldX, y0 + height - capHeight / 2, worldZ);
      size.set(cell, capHeight, cell);
      buildings.write(center, size, facade.clone().multiplyScalar(0.72));
    }
  }
  group.add(buildings.mesh);

  // Window cells on exterior faces: every ~4 m storey of a column face
  // that no neighbouring column covers gets a pale portrait pane. Hero
  // envelopes yield to their referenced recognition fenestration instead of
  // receiving a second grid of generic square holes.
  const columnTops = new Map<number, number>();
  const columnKey = (x: number, z: number): number => x * 65536 + z;
  for (const [xIdx, zIdx, , y1dm] of payload.buildings) {
    const key = columnKey(xIdx, zIdx);
    columnTops.set(key, Math.max(columnTops.get(key) ?? -1e9, y1dm / 10));
  }
  type WindowFace = {
    color: Color;
    nx: number;
    nz: number;
    x: number;
    y: number;
    z: number;
  };
  const faces: WindowFace[] = [];
  const glass = new Color(VOXEL_WINDOW_GLASS);
  const glassPale = new Color(VOXEL_WINDOW_GLASS_PALE);
  const teal = new Color(VOXEL_WINDOW_TEAL);
  for (const [xIdx, zIdx, y0dm, y1dm, classId] of payload.buildings) {
    if (WINDOWLESS_CLASSES.has(payload.classes[classId] ?? "")) {
      continue;
    }
    if (voxelRecognitionAreaAt(worldXAbs(xIdx), worldZAbs(zIdx))) {
      continue;
    }
    const top = y1dm / 10;
    for (const [dx, dz] of [
      [1, 0],
      [-1, 0],
      [0, 1],
      [0, -1],
    ] as const) {
      const neighbourTop = columnTops.get(columnKey(xIdx + dx, zIdx + dz));
      const faceX = worldXAbs(xIdx) + (dx * cell) / 2 + dx * 0.08;
      const faceZ = worldZAbs(zIdx) + (dz * cell) / 2 + dz * 0.08;
      if (voxelRecognitionAreaAt(faceX, faceZ)) {
        continue;
      }
      // Storey-banded window rows: every column face carries its glass
      // on the SAME storey grid, so the facade reads as designed rows
      // rather than randomly punched holes.
      const base = y0dm / 10;
      const firstRow = Math.ceil((base + 2) / cell) * cell;
      for (let yCenter = firstRow; yCenter + 1.2 <= top; yCenter += cell) {
        if (neighbourTop !== undefined && neighbourTop >= yCenter + 1) {
          continue;
        }
        // Two glass tones alternate along the row for gentle block
        // variety; a teal accent every fourth bay keeps it lively.
        const bay = Math.abs(xIdx + zIdx);
        const color = bay % 4 === 0 ? teal : bay % 2 === 0 ? glass : glassPale;
        faces.push({
          color,
          nx: dx,
          nz: dz,
          x: faceX,
          y: yCenter,
          z: faceZ,
        });
      }
    }
  }
  if (faces.length > 0) {
    const panes = new InstancedMesh(
      new PlaneGeometry(1, 1),
      new MeshBasicMaterial({ color: 0xffffff, side: DoubleSide }),
      faces.length,
    );
    panes.name = "Voxel facade windows";
    const matrix = new Matrix4();
    faces.forEach((face, index) => {
      // Plane spans the face's tangent; dir = up × normal in the plane.
      const dirX = -face.nz;
      const dirZ = face.nx;
      matrix.set(
        dirX * VOXEL_WINDOW_WIDTH_M,
        0,
        face.nx,
        face.x,
        0,
        VOXEL_WINDOW_HEIGHT_M,
        0,
        face.y,
        dirZ * VOXEL_WINDOW_WIDTH_M,
        0,
        face.nz,
        face.z,
        0,
        0,
        0,
        1,
      );
      panes.setMatrixAt(index, matrix);
      panes.setColorAt(index, face.color);
    });
    panes.instanceMatrix.needsUpdate = true;
    if (panes.instanceColor) {
      panes.instanceColor.needsUpdate = true;
    }
    panes.frustumCulled = false;
    group.add(panes);
  }

  const trunks = instancedBoxes("Voxel tree trunks", payload.trees.length);
  const crowns = instancedBoxes("Voxel tree crowns", payload.trees.length * 2);
  for (const [xIdx, zIdx, y0dm, hdm] of payload.trees) {
    const y0 = y0dm / 10;
    const height = Math.max(cell, hdm / 10);
    const trunkHeight = Math.max(cell / 2, height - cell * 1.5);
    const species = Math.abs(xIdx * 7 + zIdx * 13) % 5;
    center.set(worldXAbs(xIdx), y0 + trunkHeight / 2, worldZAbs(zIdx));
    size.set(cell * 0.45, trunkHeight, cell * 0.45);
    // Every fifth tree is a birch (pale trunk), like a mixed park.
    trunks.write(
      center,
      size,
      species === 0
        ? new Color(0xd6dfe0)
        : shadeFor(TRUNK_SHADES, xIdx, zIdx, 1),
    );
    const crownHeight = cell * 1.9;
    center.set(
      worldXAbs(xIdx),
      y0 + trunkHeight + crownHeight / 2,
      worldZAbs(zIdx),
    );
    size.set(cell * 2.2, crownHeight, cell * 2.2);
    crowns.write(center, size, shadeFor(LEAF_SHADES, xIdx, zIdx, 2));
    // Every third tree stacks a smaller crown — the spruce silhouette.
    if (species === 1 || species === 3) {
      center.set(
        worldXAbs(xIdx),
        y0 + trunkHeight + crownHeight + cell * 0.55,
        worldZAbs(zIdx),
      );
      size.set(cell * 1.3, cell * 1.1, cell * 1.3);
      crowns.write(center, size, shadeFor(LEAF_SHADES, xIdx, zIdx, 3));
    }
  }
  group.add(trunks.mesh);
  group.add(crowns.mesh);

  // Meadow flowers: sparse deterministic colour dots on grass runs —
  // the small-scale life real Minecraft plains have.
  const FLOWER_TONES = [0xe6bd4c, 0xe79a61, 0xf7fbf7] as const;
  const grassClass = payload.classes.indexOf("grass");
  const groundTopY = groundTopSampler(payload);
  const flowerSpots: Array<[number, number, number]> = [];
  payload.ground_rows.forEach((row, zOffset) => {
    for (const [xStart, run, classId] of row) {
      if (classId !== grassClass) {
        continue;
      }
      for (let step = 0; step < run; step += 1) {
        const xOffset = xStart + step;
        const roll = Math.abs(xOffset * 2654435761 + zOffset * 40503) % 41;
        if (roll === 0) {
          flowerSpots.push([xOffset, zOffset, roll]);
        }
      }
    }
  });
  const flowers = instancedBoxes("Voxel meadow flowers", flowerSpots.length);
  for (const [xOffset, zOffset] of flowerSpots) {
    const topY = groundTopY(xOffset, zOffset);
    center.set(
      worldXAbs(payload.grid.min_x_idx + xOffset),
      topY + 0.3,
      worldZAbs(payload.grid.min_z_idx + zOffset),
    );
    size.set(0.55, 0.6, 0.55);
    flowers.write(
      center,
      size,
      new Color(
        FLOWER_TONES[
          Math.abs(xOffset * 31 + zOffset * 17) % FLOWER_TONES.length
        ],
      ),
    );
  }
  group.add(flowers.mesh);

  for (const child of group.children) {
    if (child instanceof InstancedMesh) {
      child.instanceMatrix.needsUpdate = true;
      if (child.instanceColor) {
        child.instanceColor.needsUpdate = true;
      }
      child.frustumCulled = false;
    }
  }
  return group;
}
